from pathlib import Path
import json
root=Path(__file__).resolve().parents[3];out=Path(__file__).resolve().parent
a=json.loads((out/'analysis.json').read_text(encoding='utf-8'));assert a['complete'] and (root/'docs/P9_04_POPULATION_REPORT.md').exists()
for name in ['CLAUDE.md','README.md','docs/PROGRAMME_STATE.md','docs/PROGRESS.md','docs/PHASES.md','docs/EXPLORATION_DEFENCE_PLAN.md','docs/STANDARDS.md','docs/RELIGHT-design.md']:
 p=root/name;s=p.read_text(encoding='utf-8')
 s=s.replace('P9-04 is next for implementation.', 'P9-04R is next: repair the failures measured by P9-04 before P9-05.')
 s=s.replace('P9-04 is the next implementation task.', 'P9-04R is the next implementation task, repairing the P9-04 population failures before P9-05.')
 s=s.replace('**Next implementation: P9-04.**', '**Next implementation: P9-04R — population failure repairs.**')
 s=s.replace('**Next implementation (2026-09-08, D-EX-49):** P9-04.', '**Next implementation (2026-09-08, D-EX-50):** P9-04R, addressing the measured population failures before P9-05.')
 s=s.replace('P9-04 is next for the retained 10,000-seed run, followed by engineering/human preparation.', f"[P9-04](P9_04_POPULATION_REPORT.md) completed all 10,000 seeds, retaining {a['failed']} failed seeds. P9-04R repairs those findings before P9-05 engineering/human preparation.")
 s=s.replace('P9-04 is next.', f"P9-04 completed all 10,000 declared seeds, with {a['failed']} failures retained. P9-04R repairs those findings before P9-05.")
 if name=='docs/PROGRAMME_STATE.md':
  s=s.replace('P9-01/P9-02/P9-03 implementation', 'P9-01/P9-02/P9-03 implementation and P9-04 population evidence/tooling')
  s=s.replace('## Verified work and remaining observations\n', f"## Verified work and remaining observations\n\n**P9-04 measurement complete; population validation failed:** {a['passed']:,}/{a['attempted']:,} seeds pass and {a['failed']} fail across {len(a['failureClasses'])} retained classes. 338 full + 9 focused tests, types/build/lint/docs/freshness and evidence checks pass; six ordinary freight/truck routes and 18 extraction probes pass. Seed 102's stop can be cleared by mining, but its longer unattended scenario loses two bases and freight stalls; this is not a defence pass. [Report](P9_04_POPULATION_REPORT.md). Gameplay/config/build remain byte-identical to P9-03. P9-04R repairs generation/survey findings before P9-05; human gates remain open.\n")
 if name=='docs/PROGRESS.md':
  s=s.replace('| P9-04 | Campaign seed fairness and route evidence | agent | in_progress |','| P9-04 | Campaign seed fairness and route evidence | agent | done |')
  s=s.replace('| pending — P9-04 report | |',f"| docs/P9_04_POPULATION_REPORT.md — complete 10,000-seed measurement; {a['failed']} failed seeds retained; 338 full + 9 focused tests, 6 paid routes, 18 extraction probes; repairs follow | 2026-09-08 |")
  needle='| P9-05 | City engineering review and human preparation | agent | blocked | P9-04 |'
  row='| P9-04R | Repair demonstrated campaign generation and survey failures | agent | todo | P9-04 | P9_04_POPULATION_REPORT.md: resolve measured failure classes with deterministic complete reservations/approaches; preserve saved layouts/logs, version changed generation, ordinary probes and a separate retained full 10,000-seed comparison; never overwrite the failed baseline | pending — repair and population comparison report | |\n'
  assert needle in s;s=s.replace(needle,row+needle.replace('blocked | P9-04 |','blocked | P9-04R |'))
  s+=f"\n- 2026-09-08 — P9-04 measurement/tooling done under D-EX-50: all 10,000 declared seeds attempted on unchanged gameplay; {a['passed']} pass and {a['failed']} fail in {len(a['failureClasses'])} retained classes. Source-checked resumption, active-lock/mismatch refusal, 338 full + 9 focused tests, six paid routes and 18 extraction cells verified. Seed 102 clears 300 stone and completes truck construction but loses unattended bases and stalls freight; no defence pass. P9-04R is added as the runnable repair follow-up; P9-05 stays blocked on those repairs. Historical evidence/human gates unchanged; no commit or push.\n"
 p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/DECISIONS.md';s=p.read_text(encoding='utf-8');assert '### D-EX-50 ' not in s
s+=f"\n\n### D-EX-50 — P9-04 declared population evidence and measured repair follow-up (2026-09-08)\n\n**Authority:** owner (current user), “Onto P9-04”. Complete the reviewed declared population, resumable evidence runner and ordinary representative/holdout probes.\n\n**Implementation and measurement choices (agent):** declare seeds 1–10,000 inclusive; use 12 workers, immutable checksummed seed records, source/runtime/seed identity checks and explicit process-first versus warm timing. All 10,000 attempted seeds are retained: {a['passed']} pass, {a['failed']} fail in {len(a['failureClasses'])} classes. No map, gameplay rule, config fingerprint or acceptance check was changed to improve this result. [Report](P9_04_POPULATION_REPORT.md) distinguishes passing code/short paid probes from the failed population and longer unattended seed-102 scenario.\n\n**Follow-up (agent):** P9-04R records the demonstrated generation/survey repairs before P9-05. Preserve this baseline and old saves/logs, version future generation changes, exercise the failure classes and retain a fresh complete population comparison. This records required engineering work, not approval of new progression or a waived validator check. Human ten-seed/shared play, RI-02B after P9-05, Q07 and performance obligations remain separate. No human verdict, commit or push is authorised by this measurement.\n"
p.write_text(s,encoding='utf-8',newline='\n');print('Handoff updated; failed population remains explicit and repairs precede P9-05.')
