from pathlib import Path
import json
root=Path(__file__).resolve().parents[4];out=Path(__file__).resolve().parent
read=lambda p:p.read_text(encoding='utf-8-sig')
assert '# pass 359' in read(out/'test.log') and '# fail 0' in read(out/'test.log')
assert '# pass 22' in read(out/'focused.log') and '# fail 0' in read(out/'focused.log')
b=json.loads(read(out/'browser-result.json'));r=json.loads(read(out/'regression-browser-result.json'))
assert len(b['rows'])==5 and not b['errors'] and len(r['rows'])==2 and not r['errors']
for n in ['CLAUDE.md','README.md','docs/PROGRAMME_STATE.md','docs/PHASES.md','docs/EXPLORATION_DEFENCE_PLAN.md','docs/STANDARDS.md']:
 p=root/n;s=read(p).replace('RI-02B-UI-02 is next','RI-02B-UI-03 is next')
 if n=='CLAUDE.md':
  a=s.index('Current task pointer:');z=s.index('\n\n',a);s=s[:a]+'Current task pointer: RI-02B-UI-03 is next: build catalogue, stable quickbar and placement feedback. UI-01 shell/input and UI-02 core HUD/contextual interaction/objectives are complete; evidence is in docs/evidence/ui-redesign/README.md. P9-05 remains frozen on port 5181 and P9-H remains available. PROGRESS owns execution order.'+s[z:]
 if n=='README.md':
  s=s.replace('UI-01 shell/input foundations','UI-01 shell/input and UI-02 HUD/guidance')
  s=s.replace('The UI-01 shell is implemented; HUD, quickbar, inspection/projects and full settings/scaling remain in UI-02–06.','The shell, compact HUD and truthful opening guidance are implemented. Catalogue/quickbar, deeper inspection/projects and settings/scaling remain in UI-03–06.')
 if n=='docs/PROGRAMME_STATE.md':
  a=s.index('Current handoff:');z=s.index('\n\nPrior city/construction handoff:',a)
  s=s[:a]+'Current handoff: 2026-09-09. **RI-02B-UI-02 is complete:** compact campaign HUD, discovery-filtered minimap, shared prompt/E target query, truthful opening and work-ahead guidance, one known tracked objective and camera-only location controls. [Evidence](evidence/ui-redesign/README.md); [mutable UI preview](http://127.0.0.1:5178/?rules=exploration-v2&seed=3&view=world&state=/ui-fresh.json). 359 full tests, 22 focused tests, types/build/lint and actual opening/input/save/replay/warning browser checks pass. Existing construction and crafting predicates are shared with read-only queries; save schema, gameplay costs and campaign fingerprint remain unchanged. UI-03 is next for catalogue/quickbar/placement. Human verdicts and existing performance findings remain open.'+s[z:]
  s=s.replace('and UI-01 implementation are local changes','and UI-01/UI-02 implementation are local changes').replace('now including UI-01','now including UI-02')
 p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/PROGRESS.md';s=read(p).replace('**Next implementation (2026-09-09, D-UI-03):** RI-02B-UI-02, core HUD, contextual interaction and truthful objectives. UI-01 shell/input foundations are complete','**Next implementation (2026-09-09, D-UI-04):** RI-02B-UI-03, build catalogue, stable quickbar and placement feedback. UI-01 shell/input and UI-02 HUD/guidance are complete')
s=s.replace('| RI-02B-UI-02 | Core HUD, contextual interaction and objective guidance | agent | in_progress |','| RI-02B-UI-02 | Core HUD, contextual interaction and objective guidance | agent | done |').replace('| RI-02B-UI-03 | Build catalogue, stable quickbar and placement feedback | agent | blocked |','| RI-02B-UI-03 | Build catalogue, stable quickbar and placement feedback | agent | todo |')
s='\n'.join(line.replace('pending — docs/evidence/ui-redesign/README.md | |','docs/evidence/ui-redesign/README.md UI-02; ui-02/verification.json | 2026-09-09 |') if line.startswith('| RI-02B-UI-02 |') else line for line in s.splitlines())+'\n'
s+='\n- 2026-09-09 — RI-02B-UI-02 done under D-UI-04: compact HUD/minimap, shared contextual E resolver, truthful supplies/operating-machine/rebuild/recovery guidance and known objective tracking. 359 full + 22 focused tests, types/build/lint, both-width opening and shell input/save/replay, prepared-state and natural-warning/Pause checks pass. UI-03 blocked → todo. Frozen P9/EX-08D evidence and human gates remain intact; no commit or push.\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/DECISIONS.md';s=read(p);assert '### D-UI-04 ' not in s
s+='\n### D-UI-04 — UI-02 core HUD and truthful next actions (2026-09-09)\n\n**Authority:** owner (current user), “Ok lets move to UI-02”. Implements the adopted D-UI-01 specification after UI-01 under D-UI-02. This is implementation authority, not a human gameplay verdict.\n\n**Implementation choices (agent):** a single DOM campaign HUD replaces the four canvas corners. Existing clock/speed, warnings, names, navigation and discovery filters remain authoritative. A read-only sim query selects the same action for the prompt and E: pointed object first; otherwise reachable Home supplies first, then the nearest available interaction. Down prevents interaction; repairs retain priority over the damaged object. Existing commands and transfers enforce payment/reach. Construction affordability and hand-craft availability are extracted from their existing validators, with unchanged costs/queue behaviour. Opening guidance follows carried stock, real Home stock, existing machine operation, saved production and restoration; no quest/save schema or persistent UI achievement is added. The opening ID is distinct from the later repair workshop. Projects exposes one optional known objective; selection and Show location remain presentation only. Warnings use amber ahead of dusk and danger colour for active raids/assaults.\n\n**Evidence/handoff:** [UI-02 evidence](evidence/ui-redesign/README.md) records 359 full and 22 focused tests, types/build/lint, actual two-width opening/shell/save/replay checks, prepared states and natural warning visible in Pause. UI-03 is next. Final catalogue, deeper inspection/restoration, settings/scaling, formal human review, existing performance findings and Q07 remain separate. Frozen P9/EX-08D evidence, save schema and campaign fingerprint ba11e896 are preserved. No commit or push.\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/RI-02B_UI_SPEC.md';s=read(p);s+='\n- 2026-09-09 — D-UI-04 / UI-02: core HUD, bounded known-destination minimap, shared sim interaction selection and structured campaign next actions delivered. Opening/known-objective tracking is presentation only; catalogue, deeper inspection/restoration and settings remain in their own tasks. [Evidence](evidence/ui-redesign/README.md).\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/RELIGHT-design.md';s=read(p).replace('UI-01 now delivers the shared shell/input and token foundations; HUD, catalogue, inspection/projects and settings remain planned.','UI-01/UI-02 deliver the shared shell/input, tokens, core HUD and truthful opening guidance; catalogue, deeper inspection/projects and settings remain planned.');s+='\n- 2026-09-09 — D-UI-04: UI-02 HUD, contextual interaction and next-action guidance delivered; no costs, save schema or campaign progression gates changed.\n';p.write_text(s,encoding='utf-8',newline='\n')
print('Updated UI-02 handoff; UI-03 next; human gates preserved.')
