import { shortcut } from './controls';
import type { MachineState } from '@relight/sim';
export const FACTORY_STATUS_GLYPH:Record<MachineState,string>={running:'▶',starved:'○',blocked:'■',idle:'–',off:'✕'};
/** Shared English factory presentation and formatters. No translation or language-selection claim. */
export const FACTORY_TEXT = {
  buildTitle: 'Build menu', undo: 'Undo construction', redo: 'Redo construction',
  routingTitle: 'Routing settings', filter: 'Inserter item filter', priority: 'Splitter output priority',
  routingHint: 'A filter applies to the next pickup; a held item is delivered first. Splitter priority falls back when blocked. T cycles the setting under the pointer.',
  pathHint: 'Drag belts to preview a continuous path. Release to build; Esc cancels.',
  historyHint: 'Undo packs current contents into your pockets. Rebuilding uses carried machines or their normal material price.',
  emptyHand: 'Empty hand', rotate: 'Rotate', interact: 'Interact', pockets: 'Pockets',
  build: 'Build', map: 'Map', pipette: 'Pipette / clear',
  placed: 'Construction completed', recipeTarget: 'Point at an Assembler to change its recipe',
  release: 'Release to build', cancelled: 'Construction preview cancelled',
  buildHelp: `Left-click builds from carried machines or their material price. ${shortcut('rotate')} rotates; ${shortcut('pipette')} copies the pointed-at machine or clears the hand. Right-click with an empty hand packs a machine and its contents. ${shortcut('rifle')} equips the rifle; hold left-click to fire.`,
  pocketHelp: 'Take supplies from the house within reach. Build from carried materials; right-click a machine to recover it and its contents. Restoration uses carried materials and local or connected power.',
  pocketTitle: `Pockets and the chest (${shortcut('pockets')} / Tab; ${shortcut('interact')} on a house, Supply chest or Tram stop targets it)`,
  putAll: 'Put all', take: (n: number) => `Take ${n}`,
  picked: (kind: string) => `${kind} in hand — left-click builds, ${shortcut('rotate')} rotates, right-click clears the hand`,
  toolTitle: (kind: string, key: string) => `Put a ${kind} in the hand${key ? ` (${key})` : ''}`,
  price: (steel: number, copper: number, concrete = 0) => `${steel} steel${copper ? ` + ${copper} Cu` : ''}${concrete ? ` + ${concrete} concrete` : ''} from the pockets`,
  transfer: (n: number, item: string, where: string) => `${n} ${item} into ${where}`,
  carried: (n: number) => n > 0 ? `· ${n} carried` : '', locked: (reason: string) => reason ? ` · locked: ${reason}` : '',
  keys: `keys: ${shortcut('pause')} pause · ${shortcut('slower')} / ${shortcut('faster')} speed · ${shortcut('map')} map · Tab/${shortcut('pockets')} pockets · ${shortcut('build')} build · ${shortcut('cancel')} closes · ${shortcut('debug')} debug`,
  worldKeys: `${shortcut('north')}${shortcut('west')}${shortcut('south')}${shortcut('east')} move · ${shortcut('interact')} interact · ${shortcut('inspect')} inspect · ${shortcut('build')} build · ${shortcut('map')} map · wheel zoom`,
  inspectTitle: 'Factory inspection', itemStats: 'Item statistics', recipeLabel: 'Assembler recipe',
  statsHint: 'Produced includes extraction and crafting. Used includes recipe inputs, construction, restoration, repairs, fuel and ammunition. Transfers are not production; negative use rates mean returned recipe inputs. Totals are recorded history; rates use simulation time.',
  inspectHint: 'F inspects the machine under the pointer. E keeps its usual interaction. Settings require reach; Escape closes.',
  miningHand: 'Empty hand · hold on rubble to mine', inHand: (label: string) => `In hand: ${label}`,
  purpose: {
    underground: 'Carry items beneath up to four hidden tiles. Click input, then output; Esc cancels.',
    splitter: 'Split two rear inputs across two forward outputs. T selects balanced, left or right priority; blocked priority falls back.',
    belt: 'Carry items between machines without hand transfers.',
    inserter: 'Move one item per second across a tile. E sets an item filter; T cycles it.',
    excavator: 'Extract local resources automatically and output to the belt it faces.',
    mixer: 'Mix 2 stone into 1 concrete every 2s using 60 kW; belt inputs and inserter output.',
    barricade: '240 HP concrete defence; repair before packing. Blocks creatures until disabled.',
    assembler: 'Produce Shot magazines, Wire, Frames or Boards from supplied inputs.',
    turret: 'Defend a supplied position automatically with magazines.',
    arclamp: 'Wide 6-tile lighting; 12 kW from the connected local circuit.',
    lamp: 'Light nearby work and approaches.', pole: 'Connect local power circuits.',
    generator: 'Burn coal to power a local factory.', floodlight: 'Light a longer cone along its facing.',
    bigpole: 'Bridge a longer gap between power connections.', substation: 'Provide a physical connection point for a site.',
    chest: 'Buffer local supplies for inserters and carried transfers.',
    track: 'Extend the street route used by a tram.', tramstop: 'Request supplies and export surplus on a tram route.',
    tram: 'Carry reserved goods between stops and bring surplus back.', wall: 'Shape hostile approaches; repair damage with carried materials.',
  },
} as const;
