import {connectionText} from './machineConnections';
import {hasMachineInventory,machineInventory,machineInventoryDetail,machineTransferPreview,SHOT,nearDepot,itemName,ITEMS,KIND_LABEL,knownEquipment,chestTransferPreview,chestCount,machineById,pocketSlots,pocketUsed,invCap,stackSize,STOP_CAP,SUPPLY_CHEST_CAP,handCraftCheck,type ChestItem,type Kind,type InventoryAction,type PackStack} from '@relight/sim';
import {el} from './uiShell';
import {dispatch,type Session} from './session';
import {itemIcon} from './itemIcons';
import {draggable,draggingUi,cancelUiDrag} from './uiDrag';
type StackDrag={side:'pack'|'store';index:number;item:ChestItem;count:number;layout:string;source:number;target:number|null};
const name=(k:string)=>(KIND_LABEL as Record<string,string>)[k]??itemName(k);
const number=(n:number)=>Number.isInteger(n)?String(n):String(Math.round(n*100)/100);
/** Stack presentation reads sim allocations; transfers always recheck the live store, source and reach. */
export function createInventoryPanel(session:Session,root:HTMLElement,target:()=>number|null,freight:HTMLElement,storageOpen:()=>boolean=()=>true){
 root.classList.add('backpack-panel');const pair=el('div','inventory-pair'),notice=el('p','action-result'),info=el('section','item-detail'),art=el('div'),title=el('h3',undefined,'Select a stack'),description=el('p'),quantity=el('input'),ql=el('label',undefined,'Quantity '),transfer=el('button'),split=el('button',undefined,'Split stack'),sort=el('button',undefined,'Sort'),move=el('button',undefined,'Move to slot'),craft=el('button',undefined,'Craft magazine'),hint=el('p','hint','Drag to move · Shift-click to transfer · Select a stack for actions');notice.setAttribute('role','status');quantity.type='number';quantity.min='1';quantity.step='1';quantity.value='1';quantity.setAttribute('aria-label','Stack quantity');ql.append(quantity);info.append(art,title,description,ql,transfer,split,move,sort);const crafting=el('section','inventory-crafting'),craftProgress=el('p');crafting.append(el('h3',undefined,'Home workshop · Ammunition'),craft,craftProgress);root.replaceChildren(crafting,pair,info,notice,hint,freight);
 const sides=(['pack','store'] as const).map(side=>{const section=el('section',`inventory-side ${side}`),heading=el('h3'),capacity=el('p','inventory-capacity'),grid=el('div','inventory-grid');grid.dataset.inventorySide=side;grid.setAttribute('role','group');grid.setAttribute('aria-label',side==='pack'?'Backpack slots':'Storage stacks');heading.append(itemIcon(side==='pack'?'backpack':'chest'),document.createTextNode(side==='pack'?'Backpack':'Storage'));section.append(heading,capacity,grid);pair.append(section);return {side,section,capacity,grid,buttons:[] as HTMLButtonElement[]};});
 let selected:StackDrag|null=null,moveMode=false,lastContext='',stored:(PackStack|null)[]=[];
 const targetMachine=()=>target()===null?null:machineById(session.state,target()!);
 const storeName=()=>{const m=targetMachine();return m?KIND_LABEL[m.kind]:'Home storage';};
 const storeCount=(item:ChestItem)=>{const id=target(),m=id===null?null:machineById(session.state,id);return id!==null&&!m?0:m?hasMachineInventory(m)?(machineInventory(m)[item]??0):(m.inv[item]??0)+(m.kind==='tramstop'?(m.cargo?.[item]??0):0):chestCount(session.state,item);};
 const snapshot=(side:'pack'|'store',index:number):StackDrag|null=>{const slots=side==='pack'?pocketSlots(session.state.engineer):stored,s=slots[index];if(!s||s.reserved)return null;return {side,index,item:s.item as ChestItem,count:s.count,layout:JSON.stringify(slots),source:side==='pack'?session.state.engineer.inv[s.item]??0:storeCount(s.item as ChestItem),target:target()};};
 function showSelected(p:StackDrag){selected=p;quantity.value=String(Math.max(1,Math.floor(p.count/2)));moveMode=false;details();info.scrollIntoView({block:'nearest'});}
 function details(){const p=selected;art.hidden=!p;art.replaceChildren(...(p?[itemIcon(p.item)]:[]));title.textContent=p?name(p.item):'Select a stack';description.textContent=p?!Number.isFinite(p.source)?'Unlimited Home supply · transfer one kit at a time':`${number(p.count)} / ${stackSize(p.item)} in this stack · ${p.side==='pack'?'Backpack':'Storage'}`:'Your carried items stay with the engineer.';ql.hidden=transfer.hidden=split.hidden=move.hidden=!p;if(!p)return;quantity.max=String(Math.floor(p.count));transfer.hidden=!storageOpen();transfer.textContent=p.side==='pack'?`Load into ${storeName()}`:'Take into Backpack';split.hidden=move.hidden=p.side!=='pack';split.disabled=p.count<=1||p.item==='kit';move.disabled=p.item==='kit';}
 function inv(a:InventoryAction){notice.textContent=dispatch(session,{type:'inventory',action:a}).reason;selected=null;moveMode=false;update();}
 function relocate(p:StackDrag,to:number,splitStack=false){inv({type:splitStack?'split':'move',from:p.index,to,item:p.item,count:p.count,layout:p.layout,...(splitStack?{n:Number(quantity.value)}:{})});}
 function send(p:StackDrag,n:number){
  if(!storageOpen()||p.target!==target()){notice.textContent='Store changed; select the stack again.';return;}
  const st=session.state,id=target(),m=id===null?null:machineById(st,id);if(id!==null&&!m){notice.textContent='Store removed. Select another store.';return;}
  if(!Number.isSafeInteger(n)||n<=0){notice.textContent='Choose a whole positive quantity.';return;}
  const current=p.side==='pack'?st.engineer.inv[p.item]??0:storeCount(p.item);if((!(m&&hasMachineInventory(m)&&p.side==='store')&&current!==p.source)||(p.side==='pack'&&JSON.stringify(pocketSlots(st.engineer))!==p.layout)){notice.textContent='Source stack changed. Select it again.';return;}
  const requested=Math.min(n,p.count),r=dispatch(session,{type:'factory',action:{...(m&&hasMachineInventory(m)?{type:'machineTransfer' as const,id:m.id,put:p.side==='pack'}:{type:p.side==='pack'?'chestPut' as const:'chestTake' as const}),item:p.item,n:requested,...(Number.isFinite(p.source)&&!(m&&hasMachineInventory(m)&&p.side==='store')?{expected:{total:p.source,...(p.side==='pack'?{layout:p.layout,slot:p.index}:{})}}:{}),...(m?{x:m.x,y:m.y}:{})}});
  notice.textContent=r.ok?`${number(r.moved??0)} of ${number(requested)} ${name(p.item)} transferred.${(r.moved??0)<requested?' Remaining items stay at the source.':''}`:r.reason;selected=null;update();
 }
 transfer.onclick=()=>{if(selected)send(selected,Number(quantity.value));};split.onclick=()=>{if(!selected)return;const to=pocketSlots(session.state.engineer).findIndex(s=>s===null);if(to<0){notice.textContent='Backpack is full; splitting needs an empty slot.';return;}relocate(selected,to,true);};sort.onclick=()=>inv({type:'sort'});move.onclick=()=>{moveMode=true;notice.textContent='Choose a backpack destination slot.';};craft.onclick=()=>{notice.textContent=dispatch(session,{type:'factory',action:{type:'craft',item:'magazine',count:1}}).reason;update();};
 function update(){
  if(root.closest('[hidden]'))return;
  const st=session.state,context=`${storageOpen()}:${target()}`;if(context!==lastContext){cancelUiDrag();lastContext=context;selected=null;notice.textContent='';}
  root.closest('.ui-drawer')?.classList.toggle('storage-window',storageOpen());
  const header=root.closest('.ui-drawer')?.querySelector('header h2');if(header)header.textContent=storageOpen()?`${storeName()} & Backpack`:'Backpack';
  const m=target()===null?null:machineById(st,target()!),items=[...new Set([...ITEMS,...(st.campaign?[]:['kit']),...Object.keys(m?.inv??{}),...Object.keys(m?.cargo??{})])].filter(k=>(k!=='kit'||!st.campaign)&&(!(k in KIND_LABEL)||knownEquipment(st,k as Kind)));
  hint.textContent=m?connectionText(m,st):'Drag to move · Shift-click to transfer · Select a stack for actions';
  stored=[];for(const item of items){let n=storeCount(item as ChestItem);if(!Number.isFinite(n)){stored.push({item,count:1});continue;}while(n>0&&stored.length<600){const count=Math.min(n,stackSize(item));stored.push({item,count});n-=count;}}
  if(!stored.length)stored=Array.from({length:8},()=>null);
  const pack=pocketSlots(st.engineer);for(const side of sides){const isPack=side.side==='pack',cells=isPack?pack:stored;side.section.hidden=!isPack&&!storageOpen();if(!isPack)side.section.querySelector('h3')!.lastChild!.textContent=storeName();side.capacity.textContent=isPack?`${pocketUsed(st.engineer)} / ${invCap(st.engineer)} slots`:target()!==null&&!m?'Store removed':m?hasMachineInventory(m)?machineInventoryDetail(m):m.kind==='tramstop'?`Platform ${Object.values(m.inv).reduce((a,b)=>a+b,0)}/${STOP_CAP} · Arrivals ${Object.values(m.cargo??{}).reduce((a,b)=>a+b,0)}/${STOP_CAP}`:`${Object.values(m.inv).reduce((a,b)=>a+b,0)} / ${SUPPLY_CHEST_CAP} items`:'Home · supplies remain here until collected';
   if(!draggingUi())while(side.buttons.length>cells.length)side.buttons.pop()!.remove();
   while(side.buttons.length<cells.length){const i=side.buttons.length,b=el('button','inventory-slot');b.dataset.stackIndex=String(i);b.dataset.side=side.side;side.grid.append(b);side.buttons.push(b);
    b.onclick=e=>{const p=snapshot(side.side,i);if(moveMode&&selected&&isPack){relocate(selected,i);return;}if(p){if(e.shiftKey&&storageOpen())send(p,Math.max(1,Math.floor(p.count)));else showSelected(p);}};
    draggable(b,()=>{const value=snapshot(side.side,i);return value?{item:value.item,count:value.count,value}:null;},(target,p)=>{const dest=target?.closest<HTMLElement>('[data-inventory-side]');if(dest&&(dest.dataset.inventorySide==='pack'||storageOpen())&&(p.side!==dest.dataset.inventorySide||p.side==='pack')){(target?.closest('.inventory-slot')??dest).classList.add('drop-target');return p.side===dest.dataset.inventorySide?'Move stack':p.side==='pack'?`Load into ${storeName()}`:'Take into Backpack';}return 'Release to cancel';},(target,p)=>{const dest=target?.closest<HTMLElement>('[data-inventory-side]');if(!dest)return;if(dest.dataset.inventorySide!==p.side){send(p,Math.max(1,Math.floor(p.count)));}else if(p.side==='pack'){const cell=target?.closest<HTMLElement>('[data-stack-index]');if(cell)relocate(p,Number(cell.dataset.stackIndex));}});
   }
   cells.forEach((cell,i)=>{const unlimited=!isPack&&!!cell&&!Number.isFinite(storeCount(cell.item as ChestItem)),b=side.buttons[i],key=JSON.stringify(cell)+unlimited;if(b.dataset.content!==key){b.dataset.content=key;b.replaceChildren(...(cell?[itemIcon(cell.item),el('span','stack-count',cell.reserved?'Reserved':unlimited?'∞':number(cell.count))]:[]));}b.setAttribute('aria-label',`${isPack?'Backpack':'Storage'} slot ${i+1}: ${cell?`${name(cell.item)} ${cell.reserved?'reserved':unlimited?'unlimited supply':number(cell.count)}`:'Empty'}`);b.title=cell?`${name(cell.item)} · ${cell.reserved?'Kit reserves this slot':unlimited?'Unlimited Home supply':number(cell.count)}`:'Empty slot';b.setAttribute('aria-pressed',String(selected?.side===side.side&&selected.index===i));});
  }
  if(selected){const now=snapshot(selected.side,selected.index);if(!now||now.item!==selected.item||(selected.side==='pack'&&now.count!==selected.count)){selected=null;moveMode=false;}else if(selected.side==='store')selected=now;}
  details();if(selected&&storageOpen()){const at=m?[m.x,m.y] as [number,number]:undefined,p=m&&hasMachineInventory(m)?machineTransferPreview(st,m.id,selected.item,Math.max(1,Math.floor(selected.count)),selected.side==='pack'):chestTransferPreview(st,selected.item,Math.max(1,Math.floor(selected.count)),selected.side==='pack',at);description.textContent+=p.moved?` · up to ${number(p.moved)} can transfer`:` · ${p.reason}`;}
  const check=handCraftCheck(st);crafting.hidden=!!m||!nearDepot(st);craft.disabled=!!check.reason;craft.textContent=`Craft 1 Shot magazine · ${SHOT.inputs.steel} Steel plates + ${SHOT.inputs.copper} Copper · ${SHOT.seconds} s`;craft.title=check.reason||'Uses carried materials. Stay near Home until complete.';const h=st.flow?.hand;craftProgress.textContent=h?.crafts?`${h.crafts} magazine(s) queued · ${h.crafting?Math.ceil(Math.max(0,SHOT.seconds-h.craftProg))+' s remaining for current magazine':'waiting to start'} · keep near Home`:check.reason||`Produces ${SHOT.count} rounds in your Backpack. Load into your turret or keep for the rifle.`;
 }
 return {update};
}
