from pathlib import Path
out=Path('docs')
seeds=[(3,'Shared reference and prepared starts'),(4,'Reference comparison'),(5,'Reference comparison'),(8,'Holdout'),(11,'Holdout'),(13,'Holdout'),(80,'Previously failed facility-pad class'),(88,'Previously failed workshop/cache composition'),(102,'Previously obstructed stop; route and build access'),(842,'Previously failed recruit placement; narrow-street truck access')]
guide='''# P9 — frozen city playtest guide

Prepared 2026-09-09. **Human play: NOT RUN.** Use the [blank record](P9_SESSION_RECORD.md) for actual observations. [Engineering report](P9_05_READINESS_REPORT.md) and [build manifest](evidence/p9-05-2026-09-09/build-manifest.json) identify this checkpoint. The earlier [EX-08D guide](EX08D_SESSION_GUIDE.md), build on 5180 and blank record are preserved.

## Start and identity

[Open the fresh seed-3 city](http://127.0.0.1:5181/?rules=exploration-v2&seed=3&view=world&state=/fresh-3.json). All starts load paused. Press 1× when ready; record pauses, speed changes and assistance. Restart the frozen server from the repository with `python docs/evidence/p9-05-2026-09-09/serve.py` if needed. It serves the verified archive on loopback, independently of the mutable development build.

Build: exploration-v2, fingerprint `ba11e896`, survey revision 3, save schema 3 / campaign metadata 10; 205 source inputs match P9-04R. Port 5181 browser saves belong to this origin. Ctrl+S saves locally; Ctrl+O loads that slot. Save/export important observations before replacing a slot or starting another seed. Choose an explicit seed link below to restart its fresh fixture.

## Declared ten-seed route

These ten seeds are declared before human review. They combine reference cases, holdouts and repaired problem cases. They are a diagnostic sample, not a random estimate of enjoyment or campaign balance. Review them in the listed order, or record your actual order and reason. Splitting the review across sessions is fine; mark unfinished rows accurately.

| Seed | Fresh paused start | Coverage reason |
|---|---|---|
'''
for seed,reason in seeds:guide+=f'| {seed} | [Open seed {seed}](http://127.0.0.1:5181/?rules=exploration-v2&seed={seed}&view=world&state=/fresh-{seed}.json) | {reason} |\n'
guide+='''
For **each city**, use the same short route and record what actually happens:

1. Before opening the map, describe two places or landmarks that help distinguish this city. Walk out of home through the ordinary entrance, orient toward the known tram station, and describe which visible features you used. Record if places look interchangeable or navigation needs constant map checking.
2. At a junction, describe two routes you considered and why you chose one: distance, visible cover/threat, obstruction, salvage, or a useful place. Walk your choice using normal controls. Record backtracking, dead ends, body/building collisions and whether the alternative was meaningful. A forced single route is a valid observation, not a failure to fill the form.
3. Open Map (M) and Navigation. Rename the known station, pin a position, show the destination and return the camera to the engineer. Check that known and visited labels make sense. Save, reload and use your name/pin to return to a place. Restore a default name/remove a pin. Record confusing labels, focus/keyboard trouble, narrow-window scrolling and any accidental movement.
4. Inspect a reachable survey segment and station footprint. Identify a practical source-chest/construction site and street approach; after earning the station/truck/Foreman normally, exercise actual paid track, freight and queued delivery where reached. Record **inspected only**, **built**, **freight delivered** and **truck completed** separately. Never count a map line as proof of freight or truck access. Do not grind out ten complete campaigns merely to fill a row: unfinished paid work remains an explicit coverage gap.

Record real minutes, sim time, deaths/recovery, interventions, and any seed where this route cannot be completed. Do not substitute a different seed silently. A walkthrough is city evidence; it does not by itself pass Phase 9 or the whole campaign. No target completion time or score is imposed.

## Shared construction, transport and defence observations

The following **seed-3 assisted starts** were generated by replaying ordinary paid commands on this build, with no resource, HP, position or clock injection. They disclose locations and skip work you did not personally perform. Their times are preparation times, not your opening-performance results. All preserve complete replay logs and load paused.

| Start | Prepared state | Useful observations |
|---|---|---|
| [Construction](http://127.0.0.1:5181/?rules=exploration-v2&seed=3&view=world&state=/construction.json) | 01:35; Foreman recruited, second-area station restored; chest #4 has 68 steel / 27 copper; supplied ammunition design/order #3 waits for truck | Select the chest/order, start/pause/resume delivery, inspect shortages and completed machines, save during work and resume. Compare a similar hand-built cell with copied/queued work; record your actual commands/time/confusion. |
| [Defended network](http://127.0.0.1:5181/?rules=exploration-v2&seed=3&view=world&state=/network.json) | 39:50; three live cores, six stocked turrets, ammunition line, tram freight, radio and coal extraction | Natural warning at 40:00 for dusk 55:00. Observe warning comprehension, G/K camera controls, physical freight, fuel/ammo supply, defence, repairs/recovery and continuation beyond another dusk if reached. |
| [Optional Turbine](http://127.0.0.1:5181/?rules=exploration-v2&seed=3&view=world&state=/turbine.json) | 03:17; earlier crews and production prepared, 40 carried concrete, Turbine not restored | Read requirements, pay restoration normally and judge whether the service/reward is understandable. This reveals optional content and cannot establish unaided discovery. |

Construction begins early **without added home defence**. Both initial cores are live, but pause to read and arrange defence during play; use the separate defended network for longer combat observations. Network feeds use chests/inserters. Neither start establishes indefinite unattended survival; fuel/mining/transfers may still be needed. Supplied blueprints do not demonstrate personal design discovery.

For the unresolved direct-belt ammunition report, point the output belt into the turret footprint and note recipe, orientation, actual rounds on the belt, turret ammo before/after, power and target activity. The supplied construction cell provides one reproducible example. Automated examples pass, but the original symptom has not been reproduced or diagnosed. If it recurs, keep the affected save plus seed/time and describe the connection. Record inserter-fed and direct-belt results separately.

Use both a normal desktop window and a narrower window if practical. While the network runs at 1×, open item/recipe help and place/remove nearby lamps and poles using real supplies. Note visible pauses, input delay and camera/lighting stalls, machine count, hardware/browser and duration. Short automated samples do not close the earlier 266–300 ms findings or certify a reference machine.

## Record and decision

The [Phase 5 owner report](PHASE_5_PLAYTEST_REPORT.md) already credits successful two-assembler ammunition, tram/truck and defence/recovery play on the identified Phase 5 build. It is prior evidence, not a new P9 session. Do not duplicate it as current-build success.

Use [P9_SESSION_RECORD.md](P9_SESSION_RECORD.md) to record actual ten-seed observations and any shared P5–P8 evidence. Explicitly state the Phase 9 verdict separately from remaining gaps, ammo retest, P6/P7/P8 and EX-08 positions. RI-02B UI engineering may proceed after P9-05 under D-UI-02; no human gate is automatically passed. Wider Q07 progression/endgame remains outside this review.
'''
(out/'P9_SESSION_GUIDE.md').write_text(guide,encoding='utf-8',newline='\n')
record='''# P9 — human city and shared play record

**Status: NOT RUN.** Prepared 2026-09-09. All fields below await actual human observations. Automated engineering results belong in the [readiness report](P9_05_READINESS_REPORT.md), not this record. Follow the [guide](P9_SESSION_GUIDE.md).

## Session identity

- Player / dates / session order: **not recorded**
- Expected checkpoint: frozen port 5181, exploration-v2, fingerprint `ba11e896`, survey revision 3. Actual URL/build/save and any mismatch: **not recorded**
- Hardware, browser, window sizes, speed, pauses and duration: **not recorded**
- Fresh or assisted starts used; guide/blueprint/location help, debugging, stock/position changes or prior knowledge: **not recorded**
- Prior evidence: [owner Phase 5 success](PHASE_5_PLAYTEST_REPORT.md) already covers the identified earlier two-assembler factory, tram/truck and defence/recovery. No current P9 play is attributed to that statement.

## Ten-seed coverage

Enter actual order/time and evidence per seed. Recognition, choices and paid access are separate observations. Leave unplayed seeds NOT RUN; inspected-only work remains inspected-only.

| Seed | Actual order / duration / assistance | Places distinguished and cues | Alternatives considered / chosen route / reason | Names, pins, return and save/load | Construction / freight / truck: inspected or actually completed | Confusion, obstruction, performance / evidence | Status |
|---|---|---|---|---|---|---|---|
'''
for seed,_ in seeds:record+=f'| {seed} | — | — | — | — | — | — | NOT RUN |\n'
record+='''
Extra seeds/substitutions and reasons: **not recorded**. Ten declared seeds completed: **not recorded**. Comparable route deviations and remaining city coverage gaps: **not recorded**.

## Shared observations on this identified build

| Criterion | Actual start/seed and assistance | Observation, timing and supporting save | Result / remaining gap |
|---|---|---|---|
| Comparable manual versus copy/queue construction; repetition and clarity | — | — | NOT RUN |
| Stock shortage, local supply, truck travel/blocked access, pause/retry/manual takeover | — | — | NOT RUN |
| Freight, source extraction, ammunition production and finite fuel/materials | — | — | NOT RUN |
| Direct belt into turret; exact orientation, visible rounds and inventory change | — | — | NOT RUN |
| Inserter-fed ammo comparison | — | — | NOT RUN |
| Warning comprehension and G/K camera feedback | — | — | NOT RUN |
| Defence participation, damage, paid repair/disabled-base recovery | — | — | NOT RUN |
| Continued supply/survival beyond another dusk; interventions | — | — | NOT RUN |
| Crew/discovery information and optional Turbine service | — | — | NOT RUN |
| Narrow-window usability, key focus and unintended actions | — | — | NOT RUN |
| Live 1× lamp/pole edits with recipe help; stalls/input delay | — | — | NOT RUN |

Ammo recurrence details / affected save, or actual successful retest scope: **not recorded**.
Performance hardware, workload, duration, observed pauses and remaining concern: **not recorded**.
Other P5–P8/T18 criteria actually observed versus still missing: **not recorded**.

## Explicit human decisions

- Phase 9 verdict and reasons: **not recorded**.
- Ten-seed omissions or unresolved fairness/recognition/route issues: **not recorded**.
- P6-H / P7-H / P8-H positions, each with supporting observations: **not recorded**.
- P6-AMMO owner retest conclusion: **not recorded**.
- EX-08/T18 and performance positions: **not recorded**.
- Follow-up work requested: **not recorded**.

An automated pass, prepared start or city walkthrough does not fill these decisions. Existing human task status stays open until actual evidence and the owner's decision are recorded.
'''
(out/'P9_SESSION_RECORD.md').write_text(record,encoding='utf-8',newline='\n')
