from pathlib import Path
import json
root=Path.cwd();out=root/'docs/evidence/ui-redesign/ui-03'
read=lambda p:p.read_text(encoding='utf-8-sig')
assert '# pass 365' in read(out/'test.log') and '# fail 0' in read(out/'test.log')
assert '# pass 43' in read(out/'focused.log')
assert len(json.loads(read(out/'browser-result.json'))['rows'])==4
assert len(json.loads(read(out/'regression-browser-result.json'))['rows'])==2
for n in ['CLAUDE.md','README.md','docs/PROGRAMME_STATE.md','docs/PHASES.md','docs/EXPLORATION_DEFENCE_PLAN.md','docs/STANDARDS.md']:
 p=root/n;s=read(p).replace('RI-02B-UI-03 is next','RI-02B-UI-04 is next')
 if n=='CLAUDE.md':
  a=s.index('Current task pointer:');z=s.index('\n\n',a);s=s[:a]+'Current task pointer: RI-02B-UI-04 is next: machine inspection, inventory and diagnostics. UI-01 shell/input, UI-02 HUD/guidance and UI-03 catalogue/quickbar/placement are complete; evidence is in docs/evidence/ui-redesign/README.md. P9-05 remains frozen on port 5181 and P9-H remains available. PROGRESS owns execution order.'+s[z:]
 if n=='README.md':
  s=s.replace('**Next implementation: RI-02B-UI-02 — core HUD, contextual interaction and truthful objectives.**','**Next implementation: RI-02B-UI-04 — machine inspection, inventory and diagnostics.**').replace('UI-01 shell/input and UI-02 HUD/guidance','UI-01–03 shell, HUD and building controls').replace('The shell, compact HUD and truthful opening guidance are implemented. Catalogue/quickbar, deeper inspection/projects and settings/scaling remain in UI-03–06.','The shell, compact HUD, truthful opening guidance, build catalogue and customisable quickbar are implemented. Deeper inspection/projects and settings/scaling remain in UI-04–06.')
 if n=='docs/PROGRAMME_STATE.md':
  a=s.index('Current handoff:');z=s.index('\n\nPrior city/construction handoff:',a)
  s=s[:a]+'Current handoff: 2026-09-09. **RI-02B-UI-03 is complete:** discovery-filtered grouped catalogue, ten stable editable quickbar slots, browser-only versioned preferences, real pocket stock/cost/shortage and one cursor placement reason. Existing paid placement, rotation/repetition, packing and blueprint adapters remain available. [Evidence](evidence/ui-redesign/README.md); [mutable UI preview](http://127.0.0.1:5178/?rules=exploration-v2&seed=3&view=world&state=/ui-fresh.json). 365 full tests, 43 focused tests, types/build/lint and both-width paid placement/input/save/replay checks pass. The source/build archive binds 212 inputs and 12 changes against UI-02. UI-04 is next for machine inspection, inventory and diagnostics. Save schema, costs, city generation and campaign fingerprint remain unchanged. Human verdicts and existing performance findings remain open.'+s[z:]
  s=s.replace('and UI-01/UI-02 implementation are local changes','and UI-01–03 implementation are local changes').replace('now including UI-02','now including UI-03')
 p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/PROGRESS.md';s=read(p).replace('**Next implementation (2026-09-09, D-UI-04):** RI-02B-UI-03, build catalogue, stable quickbar and placement feedback. UI-01 shell/input and UI-02 HUD/guidance are complete','**Next implementation (2026-09-09, D-UI-05):** RI-02B-UI-04, machine inspection, inventory and diagnostics. UI-01–03 shell, HUD and building controls are complete')
s=s.replace('| RI-02B-UI-03 | Build catalogue, stable quickbar and placement feedback | agent | in_progress |','| RI-02B-UI-03 | Build catalogue, stable quickbar and placement feedback | agent | done |').replace('| RI-02B-UI-04 | Machine inspection, inventory and diagnostics | agent | blocked |','| RI-02B-UI-04 | Machine inspection, inventory and diagnostics | agent | todo |')
s='\n'.join(line.replace('pending — docs/evidence/ui-redesign/README.md | |','docs/evidence/ui-redesign/README.md UI-03; ui-03/verification.json | 2026-09-09 |') if line.startswith('| RI-02B-UI-03 |') else line for line in s.splitlines())+'\n'
s+='\n- 2026-09-09 — RI-02B-UI-03 done under D-UI-05: grouped discovered catalogue, stable editable ten-slot quickbar, browser-only preferences and exact placement feedback. 365 full + 43 focused tests, types/build/lint, both-width paid placement/packing/blueprint adapters and shell input/save/replay checks pass. UI-04 blocked → todo. Frozen evidence and human gates remain intact; no commit or push.\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/DECISIONS.md';s=read(p);assert '### D-UI-05 ' not in s
s+='\n### D-UI-05 — UI-03 building controls and stable shortcuts (2026-09-09)\n\n**Authority:** owner (current user), “Ok onto UI-03”. Implements D-UI-01 after UI-01/UI-02. This is implementation authority, not a human gameplay verdict.\n\n**Implementation choices (agent):** Equipment groups Production/Logistics/Power/Defence; Infrastructure and Library retain existing blueprint/history controls. A read-only sim knowledge projection hides unknown plans and exposes discovered locked requirements. Ten fixed slots use the specified belt/inserter/excavator/assembler/turret/lamp/pole/generator/rifle/floodlight defaults on 1–9/0. Explicit assignment swaps duplicates; clear and adjacent moves preserve other positions. Unknown saved assignments remain anonymous reserved slots. Optional `relight.ui.v1` stores version-one preferences outside gameplay saves/replay, repairs malformed records on explicit edits and falls back to session-only changes when storage is unavailable. Rifle and existing letter bindings remain. UI-06 owns the rest of preferences/rebinding/scaling.\n\nStock, prices, shortages and packed-first payment use sim queries and ordinary construct commands. Selection closes the drawer and restores canvas focus; rejected placement retains the tool with one cursor reason. R/Escape/repeated building and right-click packing retain their commands. Less frequent navigation actions sit in More; its Escape/focus and existing shell input capture apply. Existing blueprint copy/queue/removal/library adapters are integrated without new construction mechanics.\n\n**Evidence/handoff:** [UI-03 evidence](evidence/ui-redesign/README.md): 365 full and 43 focused tests, types/build/lint, both-width paid placement/packing/shortcut/save/replay and input checks, preference failure checks and actual-game images. UI-04 is next. Existing save schema, campaign fingerprint ba11e896, city generation, harness and frozen UI-02/P9/EX-08D evidence remain unchanged. Formal human gates, performance findings, P6-AMMO and Q07 remain open. No commit or push.\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/RI-02B_UI_SPEC.md';s=read(p)+'\n- 2026-09-09 — D-UI-05 / UI-03: grouped discovered catalogue, stable customisable quickbar and cursor placement feedback delivered; existing paid construction/blueprint adapters preserved. Browser-only quickbar preferences begin `relight.ui.v1`; full settings/scaling remains UI-06. [Evidence](evidence/ui-redesign/README.md).\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/RELIGHT-design.md';s=read(p).replace('UI-01/UI-02 deliver the shared shell/input, tokens, core HUD and truthful opening guidance; catalogue, deeper inspection/projects and settings remain planned.','UI-01–03 deliver the shared shell/input, tokens, core HUD, truthful opening guidance and catalogue/quickbar/placement controls; deeper inspection/projects and settings remain planned.');s+='\n- 2026-09-09 — D-UI-05: UI-03 catalogue, stable shortcuts and placement feedback delivered; costs, progression, saves and paid construction unchanged.\n';p.write_text(s,encoding='utf-8',newline='\n')
print('UI-03 handoff updated; UI-04 next; human gates preserved.')
