from pathlib import Path
root=Path(__file__).resolve().parents[3]
def edit(n,a,b):
 p=root/n;s=p.read_text(encoding='utf-8-sig');assert a in s,(n,a);p.write_bytes(s.replace(a,b,1).encode('utf-8'))
p=root/'docs/DECISIONS.md';s=p.read_text(encoding='utf-8');a=s.index('| D-EX-Q09 |');b=s.index('\n',a)
s=s[:a]+'''| D-EX-Q09 | Revised Phase 7 facility/recruit catalogue and Phase 8 boundary. | decided | Owner (current user), 2026-09-07: “All looks good! Continue on with P7”, accepting PHASE_7_SCOPE_REPORT.md and the catalogue question. Local Electricians recruitment; Concrete crew with Mixer/Concrete/Barricade; riverside Turbine hall; optional Lamplighters/Arc lamp and Surveyors/district information; truthful discovery/recipe UI. Credit existing tram/radio/workshop/repair and direct turret feed. Foundry/Arsenal/Refinery/Chemist/endgame stay with wider reconciliation; Foreman/blueprint recruitment ships with working Phase 8 tools. Costs/rates/placement remain provisional; Q07 remains open. | P7-01–05 |'''+s[b:]
a=s.index('\n',s.index('| D-EX-34 |'));s=s[:a]+'''\n\n| D-EX-35 | Adopt the reviewed P7 catalogue and continue with P7-01. | decided | owner (current user) | 2026-09-07 | “All looks good! Continue on with P7”. | Q09 adopted; P7-01 implements saved recruits and explicit local Electricians recruitment with earned-unlock/save compatibility. Later increments follow PROGRESS. Post-P7 play remains required; no phase verdict, commit or push implied. |'''+s[a:];p.write_bytes(s.encode())
edit('docs/PROGRESS.md','| P7-D | Choose the revised discovery catalogue | human | todo |','| P7-D | Choose the revised discovery catalogue | human | done |')
edit('docs/PROGRESS.md','docs/DECISIONS.md D-EX-Q09 — recommendation awaiting choice | |','docs/DECISIONS.md D-EX-Q09; D-EX-35 | 2026-09-07, owner acceptance |')
edit('docs/PROGRESS.md','| P7-01 | Persistent campaign discoveries and Electricians | agent | blocked | P7-D |','| P7-01 | Persistent campaign discoveries and Electricians | agent | in_progress | P7-D; D-EX-35 |')
for n in ['CLAUDE.md','README.md','docs/PROGRESS.md']:
 edit(n,'with catalogue choice Q09 next and implementation pending.','with catalogue Q09 adopted under D-EX-35 and P7-01 underway.')
edit('docs/PROGRESS.md','P7 catalogue Q09 is next;','P7-01 follows adopted catalogue Q09;')
for n in ['docs/PHASES.md','docs/EXPLORATION_DEFENCE_PLAN.md','docs/STANDARDS.md']:
 edit(n,'catalogue Q09 is recommended pending the owner’s choice.','catalogue Q09 is adopted under D-EX-35. P7-01 implements saved recruits and local recruitment first.')
edit('docs/PHASES.md','after Q09 selection. The proposed reduced catalogue and Phase 8 Foreman boundary are recommendations until then.','under adopted Q09, including its reduced catalogue and Phase 8 Foreman boundary.')
edit('docs/RELIGHT-design.md','proposes a revised catalogue under open choice Q09; its entries and deferred Phase 8 boundary are not adopted gameplay rules until the owner chooses them.','defines the catalogue adopted under Q09/D-EX-35: Electricians; Concrete crew and Mixer/Barricades; a riverside Turbine hall; optional Lamplighters/Arc lamp and Surveyors/district information; discovery/recipe UI. Foreman recruitment and blueprint automation ship together in Phase 8. Foundry, Arsenal, Refinery/Chemist and endgame stay with wider reconciliation. Scope adoption does not claim implementation or approved tuning.')
edit('docs/RELIGHT-design.md','Survivors need no newly invented hunger, housing or social simulation.','Survivors need no newly invented hunger, housing or social simulation.\n\n**P7-01 implementation:** a seeded shelter offers in-reach Electricians recruitment on foot, permanently granting existing Floodlight and Big pole plans. Construction costs carried materials and lights require real power. Substation stays available from the start. A 24-tile clue radius and walkable one-tile reservation are provisional defaults; placement clears guarded sites, source/installation pads and surveyed routes. Metadata version 6 adds stable seen/recruited records alongside the independently owned workshop cache/guardian. Older saves retain electrical unlocks earned through the old Held/fallen rule; migrated logs remain evidence but are not claimed as current-code fresh replays. See [P7-01 evidence](P7_01_DISCOVERIES_REPORT.md).')
edit('docs/PROGRAMME_STATE.md','**Phase 7 scope review is complete; catalogue choice Q09 is next. Shared playtesting moves after P7 under D-EX-34.**','**Phase 7 catalogue Q09 is adopted; P7-01 is underway under D-EX-35. Shared playtesting follows P7 under D-EX-34.**')
edit('docs/PROGRAMME_STATE.md','**P7-D / Q09 is next:** choose or revise the proposed','**P7-D / Q09 is adopted:** the owner accepted the')
edit('docs/PROGRAMME_STATE.md','Recommended deferred boundaries are explicit; the proposal is not an owner-approved game rule yet.','The reviewed deferred boundaries are also adopted; P7-01 is the current implementation task.')
edit('docs/PROGRAMME_STATE.md','All 171 P6-03 source/test/build inputs remain unchanged, and the rebuilt six production files match its archived build.','At that review all 171 P6-03 source inputs and six production files matched the archive. P7-01 now changes source/build; that identity is historical.')
p=root/'docs/PROGRESS.md';s=p.read_text(encoding='utf-8');s+='\n- 2026-09-07 — D-EX-35: owner accepts catalogue Q09, completing P7-D. P7-01 becomes in_progress for saved recruits, local Electricians recruitment and compatible earned unlocks. Shared play remains after P7; no human verdict or commit/push claimed.\n';p.write_bytes(s.encode())
