import {test} from 'node:test';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {defenceHp,ground,rubbleAt,createCampaign,parseBlueprint,blueprintTransform,blueprintBounds,canPlace,placeable,blockOfTile,dimensions,MACHINE_SIZE,MACHINE_COST,machineAt,actionResult,truckWorkRoute,truckSegmentFits,truckFits,truckWorkProblem,conservation,stateHash,loadState,makeSave,exportBlueprintEntry,truckDescription,type SimState,type Blueprint,type Command,type Dir} from '../src/index';
import {FactoryDriver,buildBlueprint,replayInterval,savedContinuation} from '../../harness/src/blueprint';
import {power,restore} from '../../harness/src/factoryScenario';
const evidence=(name:string,data:unknown)=>{if(process.env.P8_INTEGRATION_OUT)writeFileSync(`${process.env.P8_INTEGRATION_OUT}/${name}.json`,JSON.stringify(data,null,2));};
const ammo=parseBlueprint({version:1,name:'Belt-fed ammunition cell',entities:[{id:'input',kind:'chest',x:0,y:0,dir:0},{id:'feed',kind:'inserter',x:2,y:0,dir:1},{id:'assembler',kind:'assembler',x:3,y:0,dir:0,recipe:'shot'},{id:'out',kind:'inserter',x:6,y:1,dir:1},{id:'belt',kind:'belt',x:7,y:1,dir:1},{id:'turret',kind:'turret',x:8,y:1,dir:0}]});
function send(d:FactoryDriver,c:Command){d.send(c);assert.ok(actionResult(d.state).ok,`${c.type}: ${actionResult(d.state).reason}`);}
function recruit(d:FactoryDriver,kind:'foreman'|'electricians'){const r=d.state.campaign!.recruits!.sites.find(r=>r.kind===kind)!;d.approach(r.x,r.y);d.send({type:'recruitSurvivors',id:r.id});assert.ok(r.recruitedAt>=0);}
function prepare(seed:number){const st=createCampaign(seed),d=new FactoryDriver(st),initial=structuredClone(st);d.take('steel',300);d.take('copper',150);d.take('coal',30);if(seed%2)recruit(d,'foreman');else recruit(d,'electricians');const station=st.campaign!.expansion!.station;power(d,station.block);restore(d,'station');if(!(seed%2))recruit(d,'foreman');return {st,d,initial};}
function site(st:SimState,raw:Blueprint,stationOnly=true){const t=st.campaign!.truck!,station=st.campaign!.expansion!.station;let checked=0;
 for(let rotation=0;rotation<4;rotation++){let bp=raw;for(let i=0;i<rotation;i++)bp=blueprintTransform(bp,'rotate');const b=blueprintBounds(bp);
 for(let r=4;r<=44;r+=4)for(let y=Math.floor(t.y)-r;y<t.y+r;y+=2)for(let x=Math.floor(t.x)-r;x<t.x+r;x+=2){checked++;
 if(stationOnly&&bp.entities.filter(e=>['assembler','inserter'].includes(e.kind)).some(e=>blockOfTile(st,x+e.x,y+e.y)!==station.block))continue;
 if(st.flow!.machines.some(m=>{const [w,h]=dimensions(m.kind,m.dir,MACHINE_SIZE[m.kind]);return m.x<x+b.w&&m.x+w>x&&m.y<y+b.h&&m.y+h>y;}))continue;
 if(!bp.entities.every(e=>!placeable(st,e.kind,x+e.x,y+e.y,e.dir)))continue;
 const rects=bp.entities.map(e=>{const [w,h]=dimensions(e.kind,e.dir,MACHINE_SIZE[e.kind]);return {x:x+e.x,y:y+e.y,w,h};}),route=truckWorkRoute(st,rects,8);if(route!==null)return {x,y,bp,checked,routeSteps:route.length};
 }}throw Error(`No truck-served ${raw.name} site, seed ${st.seed}, stock ${JSON.stringify(st.engineer.inv)}`);
}
function ensureSteel(d:FactoryDriver,n:number){const st=d.state,G=ground(st);let attempts=0;while((st.engineer.inv.steel??0)<n&&attempts++<8){const candidates:{x:number;y:number;distance:number}[]=[];for(let tile=0;tile<G.tw*G.th;tile++){if(!G.patch[tile])continue;const x=tile%G.tw,y=Math.floor(tile/G.tw),r=rubbleAt(st,x,y);if(r?.type==='steel'&&r.units>0)candidates.push({x,y,distance:Math.hypot(x-st.engineer.x,y-st.engineer.y)});}const p=candidates.sort((a,b)=>a.distance-b.distance)[0];assert.ok(p);d.approach(p.x,p.y);send(d,{type:'factory',action:{type:'mineAt',x:p.x,y:p.y}});d.run(n-(st.engineer.inv.steel??0)+1);send(d,{type:'factory',action:{type:'mineAt',x:-1,y:-1}});}assert.ok((st.engineer.inv.steel??0)>=n,'ordinary mining supplied required steel');}
function source(d:FactoryDriver){const st=d.state,t=st.campaign!.truck!;for(let r=3;r<9;r++)for(let y=Math.floor(t.y)-r;y<t.y+r;y++)for(let x=Math.floor(t.x)-r;x<t.x+r;x++)if(canPlace(st,'chest',x,y).ok&&truckWorkRoute(st,[{x,y,w:2,h:2}],3)!==null)return d.place('chest',x,y);throw Error('No local source chest');}
for(const seed of [3,4,5,8,11,13])test(`P8 integration seed ${seed}: repeated paid ammunition pattern, station chest, truck, powered belts and replay`,()=>{
 const began=performance.now(),{st,d,initial}=prepare(seed),supply=source(d),a=site(st,ammo);buildBlueprint(d,seed%2?a.bp:{...a.bp,entities:[...a.bp.entities].reverse()},a.x,a.y);const bounds=blueprintBounds(a.bp);send(d,{type:'blueprintCopy',from:{x:a.x,y:a.y},to:{x:a.x+bounds.w-1,y:a.y+bounds.h-1}});assert.equal(st.campaign!.clipboard!.entities.length,ammo.entities.length);
 send(d,{type:'blueprintLibrary',action:{type:'save',name:'Station ammo',folder:'Defence',icon:'turret'}});const text=exportBlueprintEntry(st,st.campaign!.plans!.library[0].id);send(d,{type:'blueprintLibrary',action:{type:'import',text}});send(d,{type:'blueprintTransform',operation:seed%2?'mirrorY':'rotate'});
 const b=site(st,st.campaign!.clipboard!); // site may rotate, so import its exact validated definition through the same portable format.
 send(d,{type:'blueprintLibrary',action:{type:'import',text:JSON.stringify({format:'relight-blueprint',version:1,name:b.bp.name,folder:'Defence',icon:'turret',blueprint:b.bp})}});
 send(d,{type:'blueprintOrder',action:{type:'queue',x:b.x,y:b.y}});const order=st.campaign!.plans!.orders.at(-1)!,cost:Record<string,number>={};for(const e of b.bp.entities)for(const [k,n] of Object.entries(MACHINE_COST[e.kind]))cost[k]=(cost[k]??0)+n;
 ensureSteel(d,cost.steel+8);
 for(const [k,n] of Object.entries(cost))assert.equal(d.put(k,n,supply),n);
 const pockets={...st.engineer.inv};send(d,{type:'truckWork',action:{type:'start',sourceId:supply.id,orderIds:[order.id]}});const phases=new Set<string>();let saved=false;const start=st.t;
 for(let i=0;i<240&&order.status!=='completed';i++){d.run(.5);const work=st.campaign!.truck!.work!;phases.add(work.phase);assert.equal(truckWorkProblem(st),'');if(work.enabled)assert.match(truckDescription(st),new RegExp(`Automatic ${work.phase}`));assert.ok(conservation(st).ok,conservation(st).problems.join(','));if(!saved&&['loading','travelling','building'].includes(work.phase)){assert.ok(savedContinuation(st,3).same);saved=true;}}
 assert.equal(order.status,'completed',st.campaign!.truck!.work!.reason);assert.deepEqual(st.engineer.inv,pockets);assert.ok(saved,'a live job checkpoint was tested');const builtSeconds=st.t-start;
 const get=(p:typeof a,id:string)=>{const e=p.bp.entities.find(e=>e.id===id);if(e)return machineAt(st,p.x+e.x,p.y+e.y)!;const kind=id==='input'?'chest':id;const v=p.bp.entities.find(e=>e.kind===kind)!;return machineAt(st,p.x+v.x,p.y+v.y)!;};
 for(const p of [a,b]){const input=get(p,'input');d.put('steel',4,input);d.put('copper',2,input);}d.run(35);
 const guns=[a,b].map(p=>get(p,'turret')),rounds=guns.map(g=>g.inv.rounds??0);assert.ok(rounds.every(n=>n>0),`turret rounds ${rounds}; made ${JSON.stringify(st.flow!.stats.made)}`);assert.ok(conservation(st).ok);
 let live:unknown=null;
 if(seed===3){const pattern=parseBlueprint({version:1,name:'Station supply and wall cell',entities:[{id:'input',kind:'chest',x:0,y:0,dir:0},{id:'feed',kind:'inserter',x:2,y:0,dir:1},{id:'belt',kind:'belt',x:3,y:0,dir:1},{id:'output',kind:'chest',x:4,y:0,dir:0},{id:'wall-a',kind:'wall',x:0,y:3,dir:0},{id:'wall-b',kind:'wall',x:1,y:3,dir:0}]}),p=site(st,pattern);ensureSteel(d,29);d.put('steel',26,supply);d.put('copper',1,supply);
 send(d,{type:'blueprintLibrary',action:{type:'import',text:JSON.stringify({format:'relight-blueprint',version:1,name:p.bp.name,folder:'Supply',icon:'chest',blueprint:p.bp})}});send(d,{type:'blueprintOrder',action:{type:'queue',x:p.x,y:p.y}});const queued=st.campaign!.plans!.orders.at(-1)!;
 d.run(Math.max(0,299.5-st.t));const raids=st.campaign!.defence!.raidsStarted;send(d,{type:'truckWork',action:{type:'start',sourceId:supply.id,orderIds:[queued.id]}});let coexist=0;
 for(let i=0;i<400&&queued.status!=='completed';i++){d.run(.25);if(st.campaign!.truck!.work!.enabled&&st.flow!.threat!.crawlers.some(c=>c.campaign?.layer==='minor'))coexist++;assert.ok(conservation(st).ok);}
 assert.equal(queued.status,'completed',st.campaign!.truck!.work!.reason);assert.ok(coexist>0);assert.ok(st.campaign!.defence!.raidsStarted>raids);const input=p.bp.entities.find(e=>e.id==='input')!,output=p.bp.entities.find(e=>e.id==='output')!,bin=machineAt(st,p.x+input.x,p.y+input.y)!,out=machineAt(st,p.x+output.x,p.y+output.y)!;d.put('steel',3,bin);d.run(8);assert.equal(out.inv.steel,3);
 live={coexistQuarterSeconds:coexist,raidsBefore:raids,raidsAfter:st.campaign!.defence!.raidsStarted,sourceChest:supply.id,delivered:out.inv.steel,walls:p.bp.entities.filter(e=>e.kind==='wall').map(e=>defenceHp(machineAt(st,p.x+e.x,p.y+e.y)!)),threat:st.flow!.threat!.stats};
 }
 const replay=replayInterval(initial,d.log,st.flow!.tick);assert.equal(stateHash(replay),stateHash(st));assert.ok(savedContinuation(st).same);
 evidence(`seed-${seed}`,{seed,assistance:'Fresh campaign opening stock plus ordinary steel mining; ordinary walks, station power/restoration and recruitment. Odd seeds Foreman before station; even seeds Electricians before station then Foreman. Odd seeds build input-first; even seeds reverse the manual and copied automatic entity order, placing the turret first. Paid source layout copied through library/import/transform, second layout constructed from a local chest by truck. Hand-filled production inputs; threats left active. Not human or unattended survival evidence.',initialStock:initial.stock,pockets:st.engineer.inv,source:supply.inv,cargo:st.campaign!.truck!.cargo,cost,live,origins:[a,b].map(p=>({x:p.x,y:p.y,checked:p.checked,routeSteps:p.routeSteps})),phases:[...phases],builtSeconds,rounds,made:st.flow!.stats.made,ledger:conservation(st),hash:stateHash(st),replay:stateHash(replay),commands:d.log.length,seconds:st.t,wallMs:performance.now()-began});
 if(seed===3&&process.env.P8_INTEGRATION_OUT)writeFileSync(`${process.env.P8_INTEGRATION_OUT}/ammo-ready.json`,JSON.stringify(makeSave(st,{log:d.log,logComplete:true,params:{seed,ruleset:'exploration-v2',map:'city',view:'world'}})));
});


test('P8 broader sweep: seeds 1–16, eight destinations, rotated placements and valid/blocked turns remain bounded and read-only',()=>{
 const rows:unknown[]=[],durations:number[]=[];let reachable=0,unreachable=0,turns=0,blockedTurns=0,placements=0;
 for(let seed=1;seed<=16;seed++){const {st}=prepare(seed),t=st.campaign!.truck!,hash=stateHash(st),routes:unknown[]=[];let valid=0,blocked=0;
 for(const [dx,dy] of [[16,0],[-16,0],[0,16],[0,-16],[24,24],[24,-24],[-24,24],[-24,-24]]){const rect={x:Math.floor(t.x)+dx,y:Math.floor(t.y)+dy,w:2,h:2},start=performance.now(),route=truckWorkRoute(st,[rect],3);durations.push(performance.now()-start);if(route===null)unreachable++;else{reachable++;let prev={x:t.x,y:t.y,dir:t.dir};for(const p of route){assert.ok(truckSegmentFits(st,prev,p));prev=p;}}routes.push({dx,dy,steps:route?.length??null,ms:durations.at(-1)});
 let bp=ammo;for(let rot=0;rot<4;rot++){if(bp.entities.every(e=>!placeable(st,e.kind,rect.x+e.x,rect.y+e.y,e.dir)))placements++;bp=blueprintTransform(bp,'rotate');}}
 for(let dy=-5;dy<=5;dy++)for(let dx=-5;dx<=5;dx++)for(const dir of [0,1,2,3] as Dir[]){const p={x:t.x+dx,y:t.y+dy,dir};if(!truckFits(st,p.x,p.y,dir))continue;const q={...p,dir:((dir+1)%4) as Dir};if(truckSegmentFits(st,p,q))valid++;else blocked++;}
 turns+=valid;blockedTurns+=blocked;assert.equal(stateHash(st),hash);rows.push({seed,validTurns:valid,blockedTurns:blocked,routes});
 }
 assert.ok(reachable>0&&unreachable>0&&turns>0&&blockedTurns>0&&placements>0);durations.sort((a,b)=>a-b);evidence('route-sweep',{method:'16 ordinary campaign preparations, 128 fixed cardinal/diagonal destination queries at offsets 16/24; 512 rotated ammunition placement probes; 11×11×4 orientation/quarter-turn probes per seed. Query results may be blocked by actual geometry. No position/stock injection; queries leave state hashes unchanged. Local headless timings, not reference-machine certification.',rows,reachable,unreachable,validTurns:turns,blockedTurns,validPlacements:placements,timing:{p50:durations[Math.floor(durations.length*.5)],p95:durations[Math.floor(durations.length*.95)],max:durations.at(-1)}});
});
