from pathlib import Path
def edit(n,a,b):
 p=Path(n);s=p.read_text(encoding='utf-8');assert a in s,(n,a);p.write_bytes(s.replace(a,b).encode('utf-8'))
old='and P7-01 complete (persistent recruits and local Electricians recruitment); P7-02 is next.'
new='and P7-01/02 complete (saved Electricians/Concrete crew, powered Mixer and paid Barricades); P7-03 is next.'
for n in ['CLAUDE.md','README.md','docs/PROGRESS.md']:edit(n,old,new)
edit('docs/PROGRESS.md','**Now (2026-09-07):**','**Now (2026-09-08):**')
edit('docs/PROGRESS.md','| P7-02 | Concrete crew, Mixer and Barricades | agent | in_progress | P7-01 |','| P7-02 | Concrete crew, Mixer and Barricades | agent | done | P7-01; D-EX-36 |')
edit('docs/PROGRESS.md','| pending — P7-02 report | |','| docs/P7_02_CONCRETE_REPORT.md | 2026-09-08 |')
edit('docs/PROGRESS.md','| P7-03 | Turbine restoration and optional lighting/survey discoveries | agent | blocked |','| P7-03 | Turbine restoration and optional lighting/survey discoveries | agent | todo |')
p=Path('docs/PROGRESS.md');p.write_bytes((p.read_text(encoding='utf-8')+'\n- 2026-09-08 — P7-02 done under D-EX-36: permanent Concrete crew recruitment, paid powered stone-to-concrete Mixer, conserved storage/routing/construction, 240-HP Barricades and paid manual/workshop repair. 262/262 tests, 19 final focused checks, typecheck/build/lint, legacy snapshot, browser controls/production/save/replay at two sizes and docs/archive verification passed. P7-03 becomes todo. Shared play remains after P7; no commit/push. See P7_02_CONCRETE_REPORT.md.\n').encode('utf-8'))
edit('docs/PROGRAMME_STATE.md','Current handoff: 2026-09-07. **Phase 7 catalogue Q09 is adopted; P7-01 is complete under D-EX-35; P7-02 is next.','Current handoff: 2026-09-08. **Phase 7 catalogue Q09 is adopted; P7-01/02 are complete under D-EX-35/36; P7-03 is next.')
edit('docs/PROGRAMME_STATE.md','P7-01 now changes source/build; that identity is historical.','P7-01/02 now change source/build; that identity is historical.')
edit('docs/PROGRAMME_STATE.md','P7-01 is implemented and verified; P7-02 is the next runnable increment.','P7-01/02 are implemented and verified; P7-03 (Turbine restoration and optional lighting/survey discoveries) is the next runnable increment.')
edit('docs/PROGRAMME_STATE.md','P7-01 freshly passed 255/255 tests,','P7-02 passed 262/262 tests plus 19 final focused checks, build/typechecks/lint, unchanged legacy snapshot, docs and archive verification. Browser checks at 1366/900 widths cover local Concrete recruitment, paid Mixer/Barricade construction, a real stone-conveyor production line, recipe inspection and save/full replay. [P7-02 report](P7_02_CONCRETE_REPORT.md) records provisional tuning, two-shelter seed coverage and version-7 compatibility.\n\nThe earlier P7-01 checkpoint passed 255/255 tests,')
for n in ['docs/PHASES.md','docs/STANDARDS.md','docs/EXPLORATION_DEFENCE_PLAN.md']:edit(n,'P7-01 implements saved recruits and local recruitment first.','P7-01/02 implement saved recruits, local Electricians/Concrete crew recruitment and the paid Mixer/Barricade chain; P7-03 is next.')
f='docs/P7_02_CONCRETE_REPORT.md'
edit(f,'- Browser verification pending final run.','- [Browser results](evidence/p7-02-2026-09-07/browser.json): isolated headless Chrome, 1366×900 and 900×900; actual panel/E recruitment, build-menu and world-click Mixer/Barricade placement, ordinary queued logistics, 40 stone becoming 20 concrete, recipe/power inspection, four concrete paid per Barricade, full replay and Ctrl+S/O equality. No page errors or horizontal overflow. Screenshots were inspected. Initial placement probes used a footprint corner and a transient camera position; correcting the test coordinates and waiting for the follow camera passed without a gameplay UI change.\n- [Manifest](evidence/p7-02-2026-09-07/manifest.json) and source/build archives identify this increment; the ordinary-command [concrete line save](evidence/p7-02-2026-09-07/concrete-line.json) retains its complete log. Prior P6/P7-01 checkpoint artifacts remain unchanged.')
edit(f,'[Focused final checks](evidence/p7-02-2026-09-07/final-focused.log) cover','[Focused final checks](evidence/p7-02-2026-09-07/final-focused.log): **19/19 passed**, covering')
