from pathlib import Path
def edit(n,a,b):
 p=Path(n);s=p.read_text(encoding='utf-8');assert a in s,(n,a);p.write_bytes(s.replace(a,b).encode('utf-8'))
edit('packages/sim/src/construction.ts',"!isChestItem(c.filter)","(!isChestItem(c.filter)||c.filter as string==='kit')")
edit('packages/sim/src/campaignDistricts.ts','nearby wall and turret repairs','nearby wall, Barricade and turret repairs')
edit('packages/game/src/panel.ts','it repairs walls and turrets within 14 tiles','it repairs walls, Barricades and turrets within 14 tiles')
edit('packages/game/src/factoryStrings.ts','Build from carried steel and copper;','Build from carried materials;')
edit('packages/sim/src/flow.ts',"(['wire', 'frame', 'board'] as const).filter(k => s[k] > 0).map(k => ` · ${k} ${Math.floor(s[k])}`)","(['wire', 'frame', 'board', 'concrete'] as const).filter(k => (s[k]??0) > 0).map(k => ` · ${k} ${Math.floor(s[k]??0)}`)")
edit('packages/sim/src/flow.ts','/** A zero count of every item (the stats ledgers). */','/** Zero counters. Concrete remains sparse in saved stats to preserve the frozen legacy state shape; read-only ledgers request all items. */')
f='packages/tools/src/campaign-docsync.ts'
edit(f,'MACHINE_COST, INSPECTION_WINDOW_TICKS','MACHINE_COST, MACHINE_SIZE, RECRUITS, recipeOf, INSPECTION_WINDOW_TICKS')
edit(f,'| Campaign metadata | Version 5; old discovery-free previews add a once-only workshop cache and delay the guardian until the engineer is away; old district-free previews add sites without changing their existing defence schedule; older defence-free previews receive protected preparation |','| Campaign metadata | Version 7; saved Electricians and Concrete crew recruitment; old earned electrical plans and existing factory/cache/defence history are retained; upgraded older logs are evidence, not current-code fresh replays |\n| Concrete crew | Separate reachable shelter; ${RECRUITS.concrete.clueRadius}-tile clue radius; recruit locally on foot, permanent plans, no new base |\n| Mixer | ${MACHINE_SIZE.mixer}×${MACHINE_SIZE.mixer}, ${MACHINE_COST.mixer.steel} steel + ${MACHINE_COST.mixer.copper} copper; ${MACHINE_KW.mixer} kW; ${recipeOf({kind:"mixer"}).inputs.stone} stone → 1 concrete every ${recipeOf({kind:"mixer"}).seconds}s; belt/inserter input, inserter output; provisional |\n| Barricade | ${MACHINE_SIZE.barricade}×${MACHINE_SIZE.barricade}, ${MACHINE_COST.barricade.steel} steel + ${MACHINE_COST.barricade.concrete} concrete; ${DEFENCE.barricadeHp} HP, no power; manual/workshop repair uses the existing paid 40-HP service; provisional |')
# Extend the existing supplied-workshop regression with the new defence, preserving the original wall case.
f='packages/sim/test/campaignDistricts.test.ts'
edit(f,"test('workshop consumes local supplies at its powered rate, pauses during attacks/outages, and preserves repairs through saves',()=>{", "for(const kind of ['wall','barricade'] as const)test(`${kind}: workshop consumes local supplies at its powered rate, pauses during attacks/outages, and preserves repairs through saves`,()=>{")
edit(f,"  const st=fixture();outposts(st);restore(st,'workshop');\n  const d=st.campaign!.districts!,w=d.workshop;", "  const st=fixture();outposts(st);restore(st,'workshop');\n  if(kind==='barricade'){const crew=st.campaign!.recruits!.sites.find(s=>s.kind==='concrete')!;crew.seenAt=0;crew.recruitedAt=0;st.engineer.inv.concrete=4;st.flow!.ledger=openLedger(st);} // Labelled finished-material fixture; full Mixer chain tested separately.\n  const d=st.campaign!.districts!,w=d.workshop;")
edit(f,"wall=nearby(st,'wall',w.x+7,w.y+4,w.block,3);", "wall=nearby(st,kind,w.x+7,w.y+4,w.block,3);")
edit(f,'damageDefence(st,wall,120);assert.match(workshopStatus(st)',"damageDefence(st,wall,kind==='wall'?120:240);assert.match(workshopStatus(st)")
edit(f,"  assert.ok(conservation(st).ok,conservation(st).problems.join(','));\n});\n\ntest('fresh campaign pays", "  if(kind==='barricade'){run(st,6);assert.equal(defenceHp(wall),200);assert.match(workshopStatus(st),/needs 2 steel/);}\n  assert.ok(conservation(st).ok,conservation(st).problems.join(','));\n});\n\ntest('fresh campaign pays")
f='docs/RELIGHT-design.md';p=Path(f);s=p.read_text(encoding='utf-8');line=next(x for x in s.splitlines() if x.startswith('**P7-01 implementation:**'));s=s.replace(line,line+'\n\n**P7-02 implementation (D-EX-36):** a separate local Concrete crew shelter permanently unlocks a paid Mixer and Barricade. Provisional Mixer: 3×3, 20 steel + 10 copper, 60 kW, 2 stone → 1 concrete every 2 seconds; belts/inserters supply input and an inserter takes finished output. Concrete is ordinary conserved cargo, stored in 50-item pocket stacks. A 1×1 Barricade costs 2 steel + 4 concrete, has 240 HP and needs no power; it blocks and can be breached by crawlers, becomes passable when disabled and uses existing paid manual/workshop repair (2 steel + 1 copper per 40 HP). Busy Mixers and damaged defences cannot be packed; completed output and intact machines can be recovered through ordinary inventory/history. Campaign metadata 7 appends the crew without moving the saved Electricians or resetting factory/defence/cache history. These values supersede legacy catalogue numbers only in the exploration profile. See [P7-02 evidence](P7_02_CONCRETE_REPORT.md).');p.write_bytes(s.encode('utf-8'))
