from pathlib import Path
def edit(n,a,b,all=False):
 p=Path(n);s=p.read_text(encoding='utf-8-sig');assert a in s,(n,a);p.write_bytes(s.replace(a,b,-1 if all else 1).encode('utf-8'))
f='packages/sim/src/flow.ts'
edit(f,"| 'splitter';", "| 'splitter' | 'mixer' | 'barricade';")
edit(f,"[...KINDS, 'wall', 'underground', 'splitter']", "[...KINDS, 'wall', 'underground', 'splitter', 'mixer', 'barricade']")
edit(f,"underground: 'Underground belt',", "mixer: 'Mixer', barricade: 'Barricade', underground: 'Underground belt',")
edit(f,"if(kind==='wall')", "if(kind==='mixer'||kind==='barricade')return !isCampaign(st)?'concrete construction belongs to the exploration campaign':campaignRecruited(st,'concrete')?'':'recruit the Concrete crew at their shelter';\n  if(kind==='wall')")
edit(f,"return ASSEMBLER_RECIPES[m.recipe ?? 'shot'];", "return m.kind==='mixer'?RECIPES.find(r=>r.name==='Concrete')!:ASSEMBLER_RECIPES[m.recipe ?? 'shot'];")
edit(f,'{ excavator: 3, belt:', '{ mixer: 3, barricade: 1, excavator: 3, belt:')
edit(f,'Record<Kind, { steel: number; copper: number }>', 'Record<Kind, { steel: number; copper: number; concrete?: number }>')
edit(f,'underground: {steel:5,copper:2}', 'mixer: {steel:20,copper:10}, barricade: {steel:2,copper:0,concrete:4},\n  underground: {steel:5,copper:2}')
edit(f,'{ excavator: 60, belt:', '{ mixer: 60, barricade: 0, excavator: 60, belt:')
edit(f,'placed: { steel: number; copper: number };','placed: { steel: number; copper: number; concrete?: number };')
edit(f,"case 'assembler':", "case 'mixer': case 'assembler':",True)
edit(f,"src.kind==='assembler'", "(src.kind==='assembler'||src.kind==='mixer')",True)
edit(f,"m.kind === 'assembler' ? recipeOutput", "(m.kind === 'assembler'||m.kind==='mixer') ? recipeOutput",True)
edit(f,"isRouting(m) || m.kind === 'wall'", "isRouting(m) || m.kind === 'barricade' || m.kind === 'wall'")
edit(f,"kind !== 'wall' && !post", "kind !== 'wall' && kind !== 'barricade' && !post")
edit(f,'cost: { steel: number; copper: number };','cost: { steel: number; copper: number; concrete?: number };')
edit(f,"export const costStr = (c: { steel: number; copper: number }): string => c.steel || c.copper ? `${c.steel} steel${c.copper ? ` + ${c.copper} Cu` : ''}` : 'nothing';", "export const costStr = (c: { steel: number; copper: number; concrete?: number }): string => c.steel || c.copper || c.concrete ? `${c.steel} steel${c.copper ? ` + ${c.copper} Cu` : ''}${c.concrete ? ` + ${c.concrete} concrete` : ''}` : 'nothing';")
edit(f,'(inv.copper ?? 0) < cost.copper)', '(inv.copper ?? 0) < cost.copper || (inv.concrete??0)<(cost.concrete??0))')
edit(f,'st.flow!.stats.placed.copper += chk.cost.copper;','st.flow!.stats.placed.copper += chk.cost.copper; if(chk.cost.concrete){pocketDrop(st.engineer,\'concrete\',chk.cost.concrete);st.flow!.stats.placed.concrete=(st.flow!.stats.placed.concrete??0)+chk.cost.concrete;}')
edit(f,"case 'wall': return `Wall", "case 'barricade': case 'wall': return `${KIND_LABEL[m.kind]}")
edit(f,"} assembler →", "} ${m.kind==='mixer'?'Mixer':'assembler'} →")
edit(f,"if (m.kind === 'depot') return { ok: false", "if(m.kind==='mixer'&&m.busy)return {ok:false,reason:'wait for the Mixer to finish before packing it',m,stacks:0,items:{}};\n  if (m.kind === 'depot') return { ok: false")
edit(f,"case 'wall': ch =", "case 'barricade': case 'wall': ch =")
edit('packages/sim/src/ledger.ts',"m.kind === 'assembler' ? recipeOutput", "(m.kind === 'assembler'||m.kind==='mixer') ? recipeOutput")
edit('packages/sim/src/ledger.ts','sinks.coal +=', 'sinks.concrete += s.placed?.concrete ?? 0;\n  sinks.coal +=')
edit('packages/sim/src/campaignDefence.ts','wallHp: 120,','barricadeHp: 240, wallHp: 120,')
edit('packages/sim/src/campaignDefence.ts',"return m.kind === 'wall' ?", "return m.kind==='barricade'?DEFENCE.barricadeHp:m.kind === 'wall' ?")
edit('packages/sim/src/campaignDefence.ts',"m!.kind==='wall'?'Wall':'Gun turret'", "m!.kind==='barricade'?'Barricade':m!.kind==='wall'?'Wall':'Gun turret'")
edit('packages/sim/src/defenceValidation.ts',"import { DEFENCE }", "import { DEFENCE, defenceMax }")
edit('packages/sim/src/defenceValidation.ts',"(m.kind==='wall'||m.kind==='turret')", "defenceMax(m)>0")
edit('packages/sim/src/defenceValidation.ts',"(m.kind!=='wall'&&m.kind!=='turret')||m.hp>(m.kind==='wall'?DEFENCE.wallHp:DEFENCE.turretHp)", "defenceMax(m)===0||m.hp>defenceMax(m)")
edit('packages/sim/src/campaignThreat.ts',"'you'|'wall'|'turret'", "'you'|'wall'|'barricade'|'turret'")
edit('packages/sim/src/campaignThreat.ts',"as 'wall'|'turret'", "as 'wall'|'barricade'|'turret'")
edit('packages/sim/src/walk.ts',"m.kind==='wall'||m.kind==='turret'", "m.kind==='wall'||m.kind==='barricade'||m.kind==='turret'")
edit('packages/sim/src/truck.ts',"m.kind==='wall'&&m.hp===0", "(m.kind==='wall'||m.kind==='barricade')&&m.hp===0")
for n in ['inspection.ts','goal.ts']:
 p='packages/sim/src/'+n;s=Path(p).read_text(encoding='utf-8');s=s.replace("m.kind==='assembler'","(m.kind==='assembler'||m.kind==='mixer')").replace("m.kind === 'assembler'","(m.kind === 'assembler'||m.kind==='mixer')")
 if n=='inspection.ts':s=s.replace("['assembler','excavator'","['mixer','assembler','excavator'")
 Path(p).write_bytes(s.encode())
# General saved recruitment now appends the Concrete crew; original shelter coordinates/history never change.
r='packages/sim/src/campaignRecruits.ts'
edit(r,"} } as const;", "}, concrete: {name:'Concrete crew',reward:'Mixer, Concrete and Barricade',clueRadius:24} } as const;")
edit(r,'version: 1; sites:', 'version: 1 | 2; sites:')
edit(r,'export function initRecruits(st: SimState): void {','function newRecruit(st: SimState, kind: RecruitKind): RecruitSite {')
edit(r,"if (!isCampaign(st) || !c || !st.flow || c.recruits) return;", "if(!c||!st.flow)throw new Error('recruit placement requires a campaign');")
edit(r,"const inherited = bi >= 0", "const inherited = kind==='electricians' && bi >= 0")
edit(r,"&& !route.has(t)", "&& (c.recruits?.sites??[]).every(s=>Math.hypot(x-s.x,y-s.y)>24)\n      && !route.has(t)")
edit(r,"if (chosen < 0) throw new Error('campaign requires an accessible Electricians shelter');", "if (chosen < 0) throw new Error(`campaign requires an accessible ${RECRUITS[kind].name} shelter`);")
edit(r,"c.recruits = { version: 1, sites: [{ id: recruitId(st.seed,'electricians'), kind:'electricians',", "return { id: recruitId(st.seed,kind), kind,")
edit(r,'inherited }] };\n  c.version = 6;', 'inherited };')
edit(r,'export function recruitAt', "export function initRecruits(st:SimState):void {\n  const c=st.campaign;if(!isCampaign(st)||!c||!st.flow||c.recruits?.version===2)return;\n  c.recruits??={version:1,sites:[]};\n  for(const kind of Object.keys(RECRUITS) as RecruitKind[])if(!c.recruits.sites.some(s=>s.kind===kind))c.recruits.sites.push(newRecruit(st,kind));\n  c.recruits.version=2;c.version=7;\n}\nexport function recruitAt")
edit(r,"return 'Walk closer to the shelter to recruit the Electricians.';", "return `Walk closer to the shelter to recruit the ${RECRUITS[s.kind].name}.`;")
edit(r,"'Electricians recruited: Floodlight and Big pole plans available. Build with carried materials and connect real power.'", "`${RECRUITS[s.kind].name} recruited: ${RECRUITS[s.kind].reward} plans available. Build with carried materials; production needs real power.`")
edit(r,"return s.recruitedAt>=0 ?", "if(s.kind==='concrete')return s.recruitedAt>=0?'Concrete crew recruited · Mixer: 2 stone → 1 concrete every 2s at 60 kW. Barricade: 2 steel + 4 concrete, 240 HP.':'Concrete crew shelter · E to recruit in person. Unlocks the Mixer and stronger concrete Barricades.';\n  return s.recruitedAt>=0 ?")
edit(r,"if(!r || r.version!==1 || !Array.isArray(r.sites) || r.sites.length!==1)", "const current=(c?.version??0)>=7;\n  if(!r || r.version!==(current?2:1) || !Array.isArray(r.sites) || r.sites.length!==(current?2:1) || new Set(r.sites.map(s=>s?.kind)).size!==r.sites.length)")
edit(r,"s.kind!=='electricians'", "!(s.kind==='electricians'||(current&&s.kind==='concrete'))")
edit('packages/sim/src/rules.ts','| 5 | 6; recruits?', '| 5 | 6 | 7; recruits?')
edit('packages/sim/src/rules.ts','[1,2,3,4,5,6].includes','[1,2,3,4,5,6,7].includes')
edit('packages/game/src/session.ts','(original.campaign?.version ?? 0) < 6','(original.campaign?.version ?? 0) < 7')
# New tools use the catalogue/build menu; no existing key is reassigned.
edit('packages/game/src/controls.ts',"wall: [],", "wall: [], mixer: [], barricade: [],")
edit('packages/game/src/factoryStrings.ts',"assembler: 'Produce", "mixer: 'Mix 2 stone into 1 concrete every 2s using 60 kW; belt inputs and inserter output.',\n    barricade: '240 HP concrete defence; repair before packing. Blocks creatures until disabled.',\n    assembler: 'Produce")
edit('packages/game/src/worldScene.ts',"splitter:0x364759, wall:", "splitter:0x364759, mixer:0x797c64, barricade:0xc1bcae, wall:")
edit('packages/game/src/worldScene.ts',"['turret', 'generator', 'excavator', 'assembler'", "['mixer','turret', 'generator', 'excavator', 'assembler'")
edit('packages/game/src/worldScene.ts',"'excavator', 'assembler', 'bigpole'", "'excavator', 'assembler', 'mixer', 'bigpole'")
edit('packages/game/src/worldScene.ts',"case 'wall': {", "case 'barricade': case 'wall': {")
edit('packages/game/src/worldScene.ts',"defenceHp(m)>0?MACHINE_COL.wall", "defenceHp(m)>0?MACHINE_COL[m.kind]")
edit('packages/game/src/worldScene.ts',"case 'assembler': {", "case 'mixer': case 'assembler': {")
edit('packages/game/src/worldScene.ts',"g.fillStyle(MACHINE_COL.assembler,", "g.fillStyle(MACHINE_COL[m.kind],")
edit('packages/game/src/worldScene.ts','recruitDescription, discoveryAt,','recruitDescription, RECRUITS, discoveryAt,')
edit('packages/game/src/worldScene.ts',"this.hooks.onToast('Recruiting the Electricians.');", "this.hooks.onToast(`Recruiting the ${RECRUITS[s.kind].name}.`);")
edit('packages/game/src/worldScene.ts',"s.recruitedAt>=0?'ELECTRICIANS / RECRUITED':'ELECTRICIANS SHELTER / E'", "`${RECRUITS[s.kind].name.toUpperCase()} / ${s.recruitedAt>=0?'RECRUITED':'E'}`")
edit('packages/game/src/panel.ts','districtGuidance, recruitDescription,','districtGuidance, RECRUITS, recruitDescription,')
edit('packages/game/src/panel.ts',"const recruitStatus = campaign ? el('p','hint') : null;\n  const recruitButton = campaign ? el('button',undefined,'Recruit Electricians') : null;", "const recruitRows:{id:string;status:HTMLElement;button:HTMLButtonElement}[]=[];")
edit('packages/game/src/panel.ts',"section.append(el('h3',undefined,'Survivor shelter'),recruitStatus!,recruitButton!);\n    recruitButton!.onclick=()=>{const s=session.state.campaign?.recruits?.sites[0];if(s)queue(session,{type:'recruitSurvivors',id:s.id});};", "section.append(el('h3',undefined,'Survivor shelters'));\n    for(const s of st.campaign!.recruits!.sites){const status=el('p','hint'),button=el('button',undefined,`Recruit ${RECRUITS[s.kind].name}`);button.onclick=()=>queue(session,{type:'recruitSurvivors',id:s.id});section.append(status,button);recruitRows.push({id:s.id,status,button});}")
p=Path('packages/game/src/panel.ts');s=p.read_text(encoding='utf-8');a=s.index('    if(recruitStatus&&recruitButton)');b=s.index('\n',a)
s=s[:a]+"    for(const row of recruitRows){const r=s.campaign?.recruits?.sites.find(r=>r.id===row.id);row.status.textContent=r&&r.seenAt>=0?recruitDescription(s,r):'Explore beyond home to find survivor shelters.';row.button.hidden=!r||r.seenAt<0;row.button.disabled=!r||!!recruitCheck(s,r.id);row.button.title=r?recruitCheck(s,r.id):'';row.button.textContent=r?`${r.recruitedAt>=0?'Recruited':'Recruit'} ${RECRUITS[r.kind].name}`:'Unknown shelter';}"+s[b:];p.write_bytes(s.encode())
edit('packages/game/src/panel.ts','${FACTORY_TEXT.price(c.steel, c.copper)}','${FACTORY_TEXT.price(c.steel, c.copper)}${c.concrete?` + ${c.concrete} concrete`:""}')
# Later metadata migration expectations: old fixtures still intentionally lack recruits entirely.
for p in Path('packages/sim/test').glob('*.test.ts'):
 s=p.read_text(encoding='utf-8');t=s.replace('campaign!.version,6','campaign!.version,7')
 if s!=t:p.write_bytes(t.encode())
