from pathlib import Path
for n in ['CLAUDE.md','README.md','docs/PROGRAMME_STATE.md','docs/PROGRESS.md','docs/PHASES.md','docs/STANDARDS.md','docs/EXPLORATION_DEFENCE_PLAN.md']:
 p=Path(n);s=p.read_text(encoding='utf-8')
 if n=='CLAUDE.md':s=s.replace('Current task pointer: RI-02B-UI-01 is next: shared visual tokens and shell/input foundations.','Current task pointer: RI-02B-UI-02 is next: core HUD, contextual interaction and truthful objectives. UI-01 shell/input foundations are complete; evidence is in docs/evidence/ui-redesign/README.md.')
 s=s.replace('RI-02B-UI-01 is next','RI-02B-UI-02 is next').replace('**Next implementation: RI-02B-UI-01 — shared visual tokens and shell/input foundations.**','**Next implementation: RI-02B-UI-02 — core HUD, contextual interaction and truthful objectives.** [UI-01 shell/input foundations](docs/evidence/ui-redesign/README.md) are complete; [current UI preview](http://127.0.0.1:5178/?rules=exploration-v2&seed=3&view=world&state=/ui-fresh.json).')
 if n=='README.md':s=s.replace('The RI-02B redesign remains pending; P9-03 adds navigation to the existing UI.','The UI-01 shell is implemented; HUD, quickbar, inspection/projects and full settings/scaling remain in UI-02–06.')
 if n=='docs/PROGRESS.md':
  s=s.replace('**Next implementation (2026-09-09, D-EX-52):** RI-02B-UI-01, shared visual tokens and shell/input foundations.','**Next implementation (2026-09-09, D-UI-03):** RI-02B-UI-02, core HUD, contextual interaction and truthful objectives. UI-01 shell/input foundations are complete with evidence in docs/evidence/ui-redesign/README.md.')
  s=s.replace('| RI-02B-UI-01 | Shared visual tokens and shell/input foundations | agent | in_progress |','| RI-02B-UI-01 | Shared visual tokens and shell/input foundations | agent | done |')
  s=s.replace('| RI-02B-UI-02 | Core HUD, contextual interaction and objective guidance | agent | blocked |','| RI-02B-UI-02 | Core HUD, contextual interaction and objective guidance | agent | todo |')
  lines=s.splitlines();lines=[line.replace('pending — docs/evidence/ui-redesign/README.md | |','docs/evidence/ui-redesign/README.md UI-01; ui-01/verification.json | 2026-09-09 |') if line.startswith('| RI-02B-UI-01 |') else line for line in lines];s='\n'.join(lines)+'\n'
  s+='\n- 2026-09-09 — RI-02B-UI-01 done under D-UI-03: shared readable tokens, full-viewport shell, existing capability adapters, one drawer, Pause/start/save surfaces and input/focus ownership. 351 tests, types/build/lint, both-width browser input/save/replay, current adapters, legacy and missing-save checks pass; actual images/contrast reviewed. No sim/harness changes; frozen P9/EX-08D evidence preserved. UI-02 blocked → todo; later UI rows and human gates remain unchanged. No commit or push.\n'
 if n=='docs/PROGRAMME_STATE.md':
  s=s.replace('Current handoff: 2026-09-09.','Current handoff: 2026-09-09. **RI-02B-UI-01 is complete:** shared tokens, full-viewport shell, preserved domain-panel adapters, one drawer, Pause/save/start surfaces and safe input/focus. [Evidence and exact change list](evidence/ui-redesign/README.md); [current mutable UI preview](http://127.0.0.1:5178/?rules=exploration-v2&seed=3&view=world&state=/ui-fresh.json). 351 full tests, types/build/lint and both-width UI input/save/replay plus adapter/legacy/missing-save checks pass. Simulation/harness/source save rules are unchanged. UI-02 is next for the HUD and opening guidance. Human verdicts/performance remain open.\n\nPrior city/construction handoff:')
  s=s.replace('The mutable development preview, now including P9-04R,','The mutable development preview, now including UI-01,')
  s=s.replace('and UI planning are local changes','and UI-01 implementation are local changes')
 p.write_text(s,encoding='utf-8',newline='\n')
p=Path('docs/RI-02B_UI_SPEC.md');s=p.read_text(encoding='utf-8');s=s.replace('This proposed file does not exist yet.','UI-01 now provides this file; [implementation evidence](evidence/ui-redesign/README.md) records its actual scope and checks.')
s+='\n## Implementation notes\n\n- 2026-09-09 — D-UI-03 / UI-01: shared tokens, shell/adapters and input/Pause foundation delivered. Candidate border changed to `#8DA79F` after its original raised-control contrast failed; measured final shared text/border pairs exceed the stated thresholds. Other token starting values and gameplay rules remain. Current objective/HUD and domain content await UI-02–05; full preferences/scaling remains UI-06. [Evidence](evidence/ui-redesign/README.md).\n';p.write_text(s,encoding='utf-8',newline='\n')
p=Path('docs/DECISIONS.md');s=p.read_text(encoding='utf-8');assert '### D-UI-03 ' not in s
s+='''
### D-UI-03 — UI-01 shared shell and input foundations (2026-09-09)

**Authority:** owner (current user), “Let’s move into RI-02B-UI-01”. Implement the adopted D-UI-01 specification after completed P9-05 under D-UI-02. Delivered-interface human approval/play is not yet recorded.

**Implementation choices (agent):** extract uiShell.ts with shared DOM controls, capability adapters, one drawer, modal Pause/start/save actions and explicit input/focus ownership. Existing simulation commands and domain panels remain authoritative. UI capture cancels unfinished belt/blueprint drags before pointer-up can commit them. The first city click while a drawer is open dismisses it without acting underneath. Camera framing reserves top/bottom/drawer space without moving the engineer. Readability refinement changes the candidate border from #69837D to #8DA79F after a failed raised-control contrast check; final shared normal-text/border minimums are 5.60:1 / 4.00:1. This is measured presentation tuning, not a core gameplay rule or comprehensive accessibility acceptance.

**Evidence/handoff:** [UI-01 evidence](evidence/ui-redesign/README.md) records 351 full tests, types/build/lint, both-width actual UI input/save/replay, adapter/legacy/missing-save checks and opened screenshots. Simulation/harness and save schema are unchanged, campaign fingerprint remains ba11e896, and frozen P9/EX-08D checkpoints remain intact. UI-01 is complete; UI-02 is next for core HUD/contextual interaction/truthful objectives. Later UI settings/content, existing performance findings, human gates and wider Q07 remain separate. No commit or push.
''';p.write_text(s,encoding='utf-8',newline='\n')
p=Path('docs/RELIGHT-design.md');s=p.read_text(encoding='utf-8');s=s.replace('These are planned changes. Costs, transfers, power, discovery and action availability stay sim-owned.','UI-01 now delivers the shared shell/input and token foundations; HUD, catalogue, inspection/projects and settings remain planned. Costs, transfers, power, discovery and action availability stay sim-owned.');s+='\n- 2026-09-09 — D-UI-03: UI-01 shell/input foundations delivered; remaining RI-02B packages retain their scope. No gameplay rule change.\n';p.write_text(s,encoding='utf-8',newline='\n')
