/** docs/EXPERIMENTS.md and docs/experiments/E*.json writers. Every row carries the run name the doc tags cite. */
import { ExperimentResult } from './util';
import { configHash, DEFAULT_CONFIG } from '@relight/sim';

const esc = (v: string | number) => String(v).replace(/\|/g, '\\|');

export function toMarkdown(results: ExperimentResult[], meta: { seeds: number[]; hours: number; date: string; seconds: number; simVersion: string }): string {
  const out: string[] = [];
  out.push('# Experiments', '',
    `Generated by \`npm run experiments\` (packages/harness) on ${meta.date}; seeds ${meta.seeds.join(', ')}; ${meta.hours} h unless a run says otherwise; ${meta.seconds.toFixed(0)} s wall clock.`,
    `Sim: @relight/sim ${meta.simVersion}, canonical config hash \`${configHash(DEFAULT_CONFIG)}\` (scattered 9 % map, wake cap, jitter ±10 %, hash hulk roll, production on, 300 starting rounds, unfed = substation N 40).`,
    'Numbers in RELIGHT-design.md tagged `[sim: E<n>-…]` come from the row of that name here. Do not edit by hand; edit the experiment and re-run.', '');
  const nFail = results.reduce((a, r) => a + r.checks.filter(c => !c.pass).length, 0);
  out.push(`## Status: ${nFail === 0 ? 'GREEN' : `RED (${nFail} failing check${nFail === 1 ? '' : 's'})`}`, '');
  out.push('| experiment | checks | failing |', '|---|---|---|');
  for (const r of results) out.push(`| ${r.id} ${esc(r.title)} | ${r.checks.length} | ${r.checks.filter(c => !c.pass).map(c => esc(c.name)).join('; ') || '-'} |`);
  out.push('');
  for (const r of results) {
    out.push(`## ${r.id} — ${r.title}`, '', `Setup: ${r.setup}. Doc sections: ${r.docRefs.join(', ')}. Python names: ${r.pyNames.join(', ')}.`, '');
    for (const s of r.sections) {
      out.push(`### ${s.title}`, '');
      if (s.note) out.push(s.note, '');
      out.push(`| ${s.header.map(esc).join(' | ')} |`, `|${s.header.map(() => '---').join('|')}|`);
      for (const row of s.rows) out.push(`| ${row.map(esc).join(' | ')} |`);
      out.push('');
    }
    out.push('### Checks', '');
    for (const c of r.checks) out.push(`- ${c.pass ? '✅' : '❌'} ${c.name} — ${c.detail}`);
    out.push('');
  }
  return out.join('\n');
}
