using System.Collections.Generic;
using Relight.UI;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UIElements;

namespace Relight.Prototypes
{
    /// <summary>
    /// B-14 / R6 — the risk prototype for "can runtime UI Toolkit do the inventory slot grid at all".
    /// KEPT CODE: this is the basis of C-06 (Backpack / storage panel). What C-06 inherits is
    /// <see cref="SlotDragController"/> (the ported uiDrag.ts state machine), the UXML/USS slot-grid layout and this
    /// wiring; what C-06 replaces is <see cref="SlotGridModel"/> — every mutation becomes a B-06 sim command, and the
    /// drop policy grows the reference's transfer / equip / quickbar branches (inventoryPanel.ts).
    ///
    /// Two grids in ONE document, 40 + 20 slots, so a drag has to cross a container boundary the way the real
    /// Backpack-to-Storage drag does.
    /// </summary>
    [DisallowMultipleComponent]
    [AddComponentMenu("Relight/Prototypes/R6 Slot Grid")]
    public sealed class SlotGridPrototype : MonoBehaviour
    {
        /// <summary>Eight retained item ids (flow.ts:159 ITEMS); the retired ones are excluded (CONTENT_CATALOGUE §17).</summary>
        public static readonly string[] Items = { "steel", "copper", "stone", "coal", "magazine", "wire", "frame", "board" };

        [SerializeField] private UIDocument document;
        [SerializeField] private EscapeChain escape;

        [Tooltip("Backpack slots. 8 x 5 = 40 (B-14 R6 spec).")]
        [SerializeField, Min(1)] private int packSlots = 40;

        [Tooltip("Storage slots. 20 (B-14 R6 spec).")]
        [SerializeField, Min(1)] private int storeSlots = 20;

        [Tooltip("Placeholder stack icons, in the order of Items. Generated by Relight/Prototypes/Build R6.")]
        [SerializeField] private Sprite[] icons = new Sprite[0];

        private readonly List<VisualElement> _packElements = new List<VisualElement>();
        private readonly List<VisualElement> _storeElements = new List<VisualElement>();
        private VisualElement _root;
        private Label _status;

        /// <summary>The in-memory slots. C-06 swaps this for the sim-backed one.</summary>
        public SlotGridModel Model { get; private set; }

        /// <summary>The drag state machine, exposed so the play-mode timing harness can drive and inspect it.</summary>
        public SlotDragController Drag { get; private set; }

        public VisualElement Root => _root;

        public IReadOnlyList<VisualElement> PackElements => _packElements;
        public IReadOnlyList<VisualElement> StoreElements => _storeElements;

        private void Awake()
        {
            if (document == null) document = GetComponent<UIDocument>();
            if (escape == null) escape = FindAnyObjectByType<EscapeChain>();
            Model = new SlotGridModel(packSlots, storeSlots);
            Model.FillAll(Items);
        }

        private void OnEnable()
        {
            _root = document != null ? document.rootVisualElement : null;
            if (_root == null) return;
            Build();
            // uiShell.ts:116 — cancel drag is the FIRST thing Escape does, before any panel closes.
            escape?.Register(new EscapeChain.Link(EscapeOrder.CancelDrag, () => Drag.Cancel()));
        }

        private void Update()
        {
            var keyboard = Keyboard.current;
            if (keyboard != null && keyboard.escapeKey.wasPressedThisFrame) escape?.Escape();
        }

        private void OnApplicationFocus(bool focused)
        {
            if (!focused) Drag?.OnApplicationFocusLost();
        }

        // ------------------------------------------------------------------ building

        private void Build()
        {
            var pack = _root.Q<VisualElement>("pack-grid");
            var store = _root.Q<VisualElement>("store-grid");
            _status = _root.Q<Label>("status");
            if (pack == null || store == null)
            {
                Debug.LogError("SlotGridPrototype: SlotGrid.uxml is missing #pack-grid or #store-grid.");
                return;
            }

            Drag = new SlotDragController(_root, BeginDrag, AddressOf, Preview, Drop);
            Drag.DragEnded += Refresh;

            _packElements.Clear();
            _storeElements.Clear();
            pack.Clear();
            store.Clear();
            for (var i = 0; i < Model.PackSlots; i++) _packElements.Add(MakeSlot(pack, new SlotAddress(SlotSide.Pack, i)));
            for (var i = 0; i < Model.StoreSlots; i++) _storeElements.Add(MakeSlot(store, new SlotAddress(SlotSide.Store, i)));
            Refresh();
        }

        private VisualElement MakeSlot(VisualElement parent, SlotAddress address)
        {
            var slot = new VisualElement { name = $"slot-{address.Side}-{address.Index}" };
            slot.AddToClassList("inventory-slot");
            slot.focusable = true;
            var icon = new VisualElement { name = "icon", pickingMode = PickingMode.Ignore };
            icon.AddToClassList("slot-icon");
            var count = new Label(string.Empty) { name = "count", pickingMode = PickingMode.Ignore };
            count.AddToClassList("stack-count");
            slot.Add(icon);
            slot.Add(count);
            parent.Add(slot);
            Drag.Attach(slot, address);
            return slot;
        }

        /// <summary>Redraw every slot from the model. Called once per accepted drop, not per frame.</summary>
        public void Refresh()
        {
            for (var i = 0; i < _packElements.Count; i++) Paint(_packElements[i], new SlotAddress(SlotSide.Pack, i));
            for (var i = 0; i < _storeElements.Count; i++) Paint(_storeElements[i], new SlotAddress(SlotSide.Store, i));
            if (_status != null)
                _status.text = $"{Model.OccupiedCount()} stacks · drag to move, drop on a full slot to swap, Escape cancels";
        }

        private void Paint(VisualElement slot, SlotAddress address)
        {
            var stack = Model.Get(address);
            var icon = slot.Q<VisualElement>("icon");
            var count = slot.Q<Label>("count");
            icon.style.backgroundImage = stack.Empty ? new StyleBackground(StyleKeyword.None) : new StyleBackground(IconFor(stack.Item));
            icon.style.visibility = stack.Empty ? Visibility.Hidden : Visibility.Visible;
            count.text = stack.Empty ? string.Empty : stack.Count.ToString();
            slot.EnableInClassList("empty", stack.Empty);
            slot.tooltip = stack.Empty ? "Empty slot" : $"{stack.Item} · {stack.Count}";
        }

        private Sprite IconFor(string item)
        {
            for (var i = 0; i < Items.Length && i < icons.Length; i++)
                if (Items[i] == item) return icons[i];
            return null;
        }

        public void SetIcons(Sprite[] sprites) => icons = sprites;

        // ------------------------------------------------------------------ the three drag callbacks (C-06 replaces these)

        private SlotStack BeginDrag(SlotAddress from) => Model.Get(from);

        private SlotAddress? AddressOf(VisualElement element) =>
            element != null && element.userData is SlotAddress a ? a : (SlotAddress?)null;

        /// <summary>The ghost's label, the reference's preview() (inventoryPanel.ts draggable preview argument).</summary>
        private string Preview(SlotAddress from, SlotAddress? to)
        {
            if (!to.HasValue) return "Release to cancel";
            if (to.Value.Equals(from)) return "Back where it was";
            var target = Model.Get(to.Value);
            if (target.Empty) return to.Value.Side == from.Side ? "Move stack" : $"Move to {to.Value.Side}";
            return $"Swap with {target.Item}";
        }

        private void Drop(SlotAddress from, SlotAddress? to)
        {
            if (!to.HasValue) return;                 // dropped on nothing: the reference cancels too
            Model.MoveOrSwap(from, to.Value);
        }
    }
}
