/** Separate generated reference for the campaign; never rewrites legacy tables. */
import { readFileSync, writeFileSync } from 'node:fs';
import { TRUCK_WORK_RULES, BLUEPRINT_LIBRARY_LIMIT, BLUEPRINT_ORDER_LIMIT, BLUEPRINT_TEXT_LIMIT, BUILD_LIMIT, HISTORY_LIMIT, SITE_CLUE_RADIUS, TURBINE, ARC_LAMP_RADIUS, UNDERGROUND_HIDDEN, SPLITTER_CAPACITY, SPLITTER_PER_S, MACHINE_COST, MACHINE_SIZE, RECRUITS, recipeOf, INSPECTION_WINDOW_TICKS, INSPECTION_SAMPLE_TICKS, TRUCK_RULES, INV_STACKS } from '@relight/sim';
import { NAVIGATION_RULES, EXPANSION_SURVEY_VERSION, CAMPAIGN_RULESET, CAMPAIGN_RULES, OPENING_LAYOUT, EXPANSION, CAMPAIGN_POWER, DEFENCE, CAMPAIGN_THREAT, DISTRICT_ECONOMY, DISCOVERY, EXCAVATOR_PER_S, MACHINE_KW } from '@relight/sim';
export function syncCampaignDocs(path: string, check: boolean): void {
  const expected = `# Campaign implementation reference

Generated by docsync from the campaign profile. The GDD remains the design authority.

| Contract | Current value / implementation |
|---|---|
| Ruleset | ${CAMPAIGN_RULESET} |
| Save schema | 3; legacy saves retain schemas 1 and 2 |
| Opening | ${CAMPAIGN_RULES.opening} |
| Starter factory frame | ${OPENING_LAYOUT.frame} × ${OPENING_LAYOUT.frame} tiles |
| Court entrance | ${OPENING_LAYOUT.gateWidth} tiles, one approach |
| Cycle | ${CAMPAIGN_RULES.daySeconds} seconds |
| Daylight | ${CAMPAIGN_RULES.daylightSeconds} seconds |
| First major assault | Night ${CAMPAIGN_RULES.firstAssaultNight}; dawn target lock, dusk finite roster |
| Legacy frontier blooms, ammo ring and claims | Disabled in this profile |
| Campaign metadata | Version 10; saved clipboard/installation knowledge, Foreman, Electricians, Concrete crew, Lamplighters, Surveyors and Turbine restoration; old earned electrical plans and existing factory/cache/defence history are retained; upgraded older logs are evidence, not current-code fresh replays |
| Discovery journal | Opening station clue; installations remembered within ${SITE_CLUE_RADIUS} tiles or through restored-route clues; only known locations on journal/map; old saves retain previously exposed locations; restoration deliveries, permanent rewards and actual service state |
| Item guide | All nine current items: implemented sources, recipe inputs/output/time/power, unlock provenance and real uses; Frames and Boards have no implemented consumer; Foreman blueprints/copy-paste are available after local recruitment |
| Foreman clipboard | Permanent local recruitment; one saved clipboard, 1–${BUILD_LIMIT} entities and 128×128-tile selection within current reach; whole-machine copy, rotation/reflection, recipes/filters/priority/underground/freight settings; atomic paid placement and ${HISTORY_LIMIT}-group history; no copied inventories/rewards; provisional limits; saved library/ghost orders and physical truck delivery available |
| Blueprint library and orders | Optional plan schema 1; ${BLUEPRINT_LIBRARY_LIMIT} entries with names/folders/catalogue icons, validated portable version-1 text up to ${BLUEPRINT_TEXT_LIMIT} characters; ${BLUEPRINT_ORDER_LIMIT} order records with monotonic IDs and independent definitions; inert ghosts can be queued before materials; missing quantities/blockers and local paid remaining-build action; cancellation/completion are terminal; no unlock, occupancy, power or inventory from plans; provisional limits |
| Turbine hall | ${TURBINE.size}×${TURBINE.size} riverside installation; ${TURBINE.cost.steel} steel + ${TURBINE.cost.copper} copper + ${TURBINE.cost.concrete} concrete delivered locally; powered commissioning; ${TURBINE.kw} kW fuel-free on its connected circuit, used before coal; local on/off switch, disabled-core isolation; no assault base; provisional |
| Lamplighters / Arc lamp | Permanent local recruitment; ${MACHINE_COST.arclamp.steel} steel + ${MACHINE_COST.arclamp.copper} copper; radius ${ARC_LAMP_RADIUS}, ${MACHINE_KW.arclamp} kW; real powered light and ordinary repair; provisional |
| Surveyors | Permanent local recruitment reveals district types on M map; does not discover rewards or provide radio attack intelligence |
| Concrete crew | Separate reachable shelter; ${RECRUITS.concrete.clueRadius}-tile clue radius; recruit locally on foot, permanent plans, no new base |
| Mixer | ${MACHINE_SIZE.mixer}×${MACHINE_SIZE.mixer}, ${MACHINE_COST.mixer.steel} steel + ${MACHINE_COST.mixer.copper} copper; ${MACHINE_KW.mixer} kW; ${recipeOf({kind:"mixer"}).inputs.stone} stone → 1 concrete every ${recipeOf({kind:"mixer"}).seconds}s; belt/inserter input, inserter output; provisional |
| Barricade | ${MACHINE_SIZE.barricade}×${MACHINE_SIZE.barricade}, ${MACHINE_COST.barricade.steel} steel + ${MACHINE_COST.barricade.concrete} concrete; ${DEFENCE.barricadeHp} HP, no power; manual/workshop repair uses the existing paid 40-HP service; provisional |
| Station restoration | ${EXPANSION.station.steel} steel + ${EXPANSION.station.copper} copper, real local/connected power; provisional cost |
| Names and navigation | Optional saved revision ${NAVIGATION_RULES.version}; ${NAVIGATION_RULES.names} name overrides of ${NAVIGATION_RULES.nameLength} characters, ${NAVIGATION_RULES.pins} pins in known districts, physical visit records; old layouts preserved, camera/selection remain presentation-only |
| Tram survey | Revision ${EXPANSION_SURVEY_VERSION} for new campaigns: buildable street tracks and complete stop footprints; old surveys and stock are retained unchanged, with incomplete replay provenance against the current new-game factory |
| Starter tram kit | One tram, two stops and route-length track, once-only station inventory |
| Physical truck | Restored second-area station; ${TRUCK_RULES.width}×${TRUCK_RULES.length} street footprint, rotates; ${TRUCK_RULES.stacks} saved cargo stacks separate from ${INV_STACKS} pocket stacks; speed ×${TRUCK_RULES.speedMultiplier}; local boarding within ${TRUCK_RULES.boardReach} tiles; valid adjacent exit; provisional |
| Area removal | Foreman; drag whole machines then explicitly pack the preview; 1–${BUILD_LIMIT} machines / 128×128 tiles; one atomic current-reach/pocket-capacity transaction; stale identities/settings refuse; contents to pockets and loose rounds to available buffer; busy/damaged/fractional/installed machines refuse; undo restores settings, not contents |
| Truck construction | Foreman + restored station truck; selected physical supply chest and up to 32 waiting orders; load within ${TRUCK_WORK_RULES.loadReach} tiles at up to ${TRUCK_WORK_RULES.loadPerSecond} items/s; real cargo, normal prices or packed machines; ${TRUCK_RULES.serviceReach}-tile service reach; one part or paired tunnel per second; swept street routes bounded to ${TRUCK_WORK_RULES.searchNodes} search nodes / ${TRUCK_WORK_RULES.pathLimit} steps; ${TRUCK_WORK_RULES.retryTicks/20}s retries; individual order pause/resume, source reassignment and immediate waiting-job retry; repeated controls preserve work; pause/resume/takeover retain cargo and built parts; provisional |
| Truck parking | Nearest clear street footprint within ${TRUCK_RULES.parkingRadius} tiles, preserving the starter kit corridor; cargo stays parked through exit/knockdown; WASD driving or Foreman construction mode; no fuel consumption; boarding pauses automatic work |
| Selected-stop map | Actual track components and existing freight manifests; ready/unpowered/full stops, tram position and interrupted service; selection is read-only |
| Underground belts | Start unlocked; each 1×1 endpoint costs ${MACHINE_COST.underground.steel} steel + ${MACHINE_COST.underground.copper} copper; up to ${UNDERGROUND_HIDDEN} hidden tiles; same-facing nearest input/output; saved stock waits on interruption; provisional |
| Priority splitters | Start unlocked; 2×1 across travel, rotates to 1×2; ${MACHINE_COST.splitter.steel} steel + ${MACHINE_COST.splitter.copper} copper; ${SPLITTER_CAPACITY}-item buffer, up to ${SPLITTER_PER_S} items/s combined; balanced/left/right with blocked-output fallback; provisional |
| Inserter filtering | Optional single item, free ordinary command; applies to the next pickup, preserves held stock |
| Radio restoration | ${EXPANSION.radio.steel} steel + ${EXPANSION.radio.copper} copper; ${CAMPAIGN_POWER.radioKw} kW after restoration; provisional values |
| Inspection rate window | Up to ${INSPECTION_WINDOW_TICKS/20} simulation seconds; samples every ${INSPECTION_SAMPLE_TICKS/20}s; optional saved campaign observations |
| Power | Physical pole links between cell substations, fueled local generators; ${CAMPAIGN_POWER.coreKw} kW per registered core |
| Major roster | ${CAMPAIGN_THREAT.majorCount} crawlers, one per ${CAMPAIGN_THREAT.spawnEvery}s; provisional tuning |
| Minor raids | Two opportunities per day, ${CAMPAIGN_THREAT.minorMin}-${CAMPAIGN_THREAT.minorMax} crawlers; no backlog |
| Major recovery | Two full cycles after actual finish; one after three connected operational bases and actual reserved home resupply (${DISTRICT_ECONOMY.resupplySteel} steel, ${DISTRICT_ECONOMY.resupplyCopper} copper, ${DISTRICT_ECONOMY.resupplyMagazines} magazines over at least ${DISTRICT_ECONOMY.resupplyVisits} ammunition visits); existing promises retained |
| Walls / turrets / cores | ${DEFENCE.wallHp} / ${DEFENCE.turretHp} / ${DEFENCE.coreHp} HP, provisional |
| Manual repair | ${DEFENCE.repairSteel} steel + ${DEFENCE.repairCopper} copper for ${DEFENCE.repairHp} HP in ${DEFENCE.repairSeconds}s; paid progress pauses out of reach |
| Disabled core recovery | ${DEFENCE.coreSteel} steel + ${DEFENCE.coreCopper} copper, ${DEFENCE.coreRepairSeconds}s after attackers leave; provisional |
| Radio warnings | Powered tower names the locked base; outage retains received information, upgrade adds approach/composition |
| Radio upgrade | ${CAMPAIGN_THREAT.radioUpgradeSteel} steel + ${CAMPAIGN_THREAT.radioUpgradeCopper} copper; provisional |
| Later station restoration | ${EXPANSION.northStation.steel} steel + ${EXPANSION.northStation.copper} copper; paid extension track/stop; provisional |
| Extraction | Distinct persistent steel/copper/coal sites; existing excavator ${EXCAVATOR_PER_S} items/s at ${MACHINE_KW.excavator} kW, real fueled power and finite output capacity; machine extraction only |
| Workshop restoration | ${EXPANSION.workshop.steel} steel + ${EXPANSION.workshop.copper} copper; ${DISTRICT_ECONOMY.workshopKw} kW; provisional |
| Workshop service | Same district within ${DISTRICT_ECONOMY.repairRadius} tiles; local chest/arrivals within ${DISTRICT_ECONOMY.supplyRadius} tiles; ${DEFENCE.repairSteel} steel + ${DEFENCE.repairCopper} copper per ${DEFENCE.repairHp} HP every ${DISTRICT_ECONOMY.repairSeconds} powered seconds; pauses for active majors and local minor raids; provisional |
| Workshop records | One persistent schematic per seed; automatic permanent field-tool fitting, no inventory slot; new manual repair duration × ${DISCOVERY.repairMultiplier}, unchanged materials; provisional |
| Workshop guardian | One Stalker lifetime, ${DISCOVERY.guardian.perception}-tile activity perception, ${DISCOVERY.guardian.leash}-tile home leash, ${DISCOVERY.guardian.windupS}s visible wind-up per strike, ${DISCOVERY.guardian.attackHp} damage; rifle/turret target; optional side yard; provisional |


Legacy generated tables and benchmarks remain in RELIGHT-design.md's legacy appendix and their existing artifact locations. Campaign artifacts use docs/experiments/campaign/ or packages/game/public/snapshots/campaign/, a campaign ConfigRef, and a hash including rules and opening geometry. Missing ruleset on a saved state means legacy; it never opts into this campaign.
`;
  if (check) {
    if (readFileSync(path, 'utf8').replace(/\r\n/g, '\n') !== expected) throw new Error('docsync: campaign reference differs; run docsync');
  } else writeFileSync(path, expected);
  console.log('docsync: exploration campaign reference matches its own profile');
}
