/** Separate generated reference for the campaign; never rewrites legacy tables. */
import { readFileSync, writeFileSync } from 'node:fs';
import { CAMPAIGN_RULESET, CAMPAIGN_RULES, OPENING_LAYOUT, EXPANSION, CAMPAIGN_POWER } from '@relight/sim';
export function syncCampaignDocs(path: string, check: boolean): void {
  const expected = `# Campaign implementation reference

Generated by docsync from the campaign profile. The GDD remains the design authority.

| Contract | Current value / implementation |
|---|---|
| Ruleset | ${CAMPAIGN_RULESET} |
| Save schema | 3; legacy saves retain schemas 1 and 2 |
| Opening | ${CAMPAIGN_RULES.opening} |
| Starter factory frame | ${OPENING_LAYOUT.frame} × ${OPENING_LAYOUT.frame} tiles |
| Court entrance | ${OPENING_LAYOUT.gateWidth} tiles, one approach |
| Cycle | ${CAMPAIGN_RULES.daySeconds} seconds |
| Daylight | ${CAMPAIGN_RULES.daylightSeconds} seconds |
| First major assault | Night ${CAMPAIGN_RULES.firstAssaultNight}, adopted target; assault system not implemented yet |
| Legacy frontier blooms, ammo ring and claims | Disabled in this profile |
| Campaign metadata | Version 2; version 1 home saves upgrade deterministically |
| Station restoration | ${EXPANSION.station.steel} steel + ${EXPANSION.station.copper} copper, real local/connected power; provisional cost |
| Starter tram kit | One tram, two stops and route-length track, once-only station inventory |
| Radio restoration | ${EXPANSION.radio.steel} steel + ${EXPANSION.radio.copper} copper; ${CAMPAIGN_POWER.radioKw} kW after restoration; provisional values |
| Power | Physical pole links between cell substations, fueled local generators; ${CAMPAIGN_POWER.coreKw} kW per registered core |
| Assault defence and radio warnings | Pending; restored radio reports readiness/outage truthfully |

Legacy generated tables and benchmarks remain in RELIGHT-design.md's legacy appendix and their existing artifact locations. Campaign artifacts use docs/experiments/campaign/ or packages/game/public/snapshots/campaign/, a campaign ConfigRef, and a hash including rules and opening geometry. Missing ruleset on a saved state means legacy; it never opts into this campaign.
`;
  if (check) {
    if (readFileSync(path, 'utf8').replace(/\r\n/g, '\n') !== expected) throw new Error('docsync: campaign reference differs; run docsync');
  } else writeFileSync(path, expected);
  console.log('docsync: exploration campaign reference matches its own profile');
}
