using Relight.Sim;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace Relight.World
{
    /// <summary>
    /// B-13. Tile class → <see cref="TileBase"/>, so the editor painter and any later importer agree on which asset
    /// stands for which terrain. Placeholder art: the five tiles this holds are flat colour squares generated by
    /// <c>Relight/Setup/Build World Scene</c> and are replaced wholesale in Phase C (C-01 imports the real region,
    /// C-06 brings the real art). The colours are the reference ground texture's, worldScene.ts:310-345.
    /// </summary>
    [CreateAssetMenu(menuName = "Relight/Tile Palette", fileName = "TilePalette")]
    public sealed class TilePalette : ScriptableObject
    {
        [Tooltip("Indexed by TileClass; Void is never painted.")]
        [SerializeField] private TileBase street;
        [SerializeField] private TileBase ground;
        [SerializeField] private TileBase rubble;
        [SerializeField] private TileBase inert;
        [SerializeField] private TileBase river;
        [SerializeField] private TileBase deposit;
        [SerializeField] private TileBase patch;

        [Tooltip("Painted over the terrain wherever ICityGeometry.Solid is true (WORLD_AND_ASSETS.md 2.6).")]
        [SerializeField] private TileBase solid;

        /// <summary>The tile asset for a terrain class, or null for <see cref="TileClass.Void"/>.</summary>
        public TileBase For(TileClass k)
        {
            switch (k)
            {
                case TileClass.Street: return street;
                case TileClass.Ground: return ground;
                case TileClass.Rubble: return rubble;
                case TileClass.Inert: return inert;
                case TileClass.River: return river;
                case TileClass.Deposit: return deposit;
                case TileClass.Patch: return patch;
                default: return null;
            }
        }

        /// <summary>The building-collision overlay tile.</summary>
        public TileBase Solid => solid;

        /// <summary>Used by the editor generator; authoring is otherwise done in the Inspector.</summary>
        public void SetTiles(TileBase newStreet, TileBase newGround, TileBase newRubble, TileBase newInert,
            TileBase newRiver, TileBase newDeposit, TileBase newPatch, TileBase newSolid)
        {
            street = newStreet; ground = newGround; rubble = newRubble; inert = newInert;
            river = newRiver; deposit = newDeposit; patch = newPatch; solid = newSolid;
        }
    }
}
