import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {createCampaign,applyCommands,advanceFlow,ground,blockOfTile,machineRunning,rubbleAt,canPlace,findPath,passable,conservation,stateProblem,actionResult,makeSave,workbenchTile,type Command,type Item,type Kind} from '../../../packages/sim/src/index';
const st=createCampaign(),G=ground(st),log:{tick:number;c:Command}[]=[],milestones:unknown[]=[];
const cmd=(c:Command)=>{log.push({tick:st.flow!.tick,c});applyCommands(st,[c]);};
cmd({type:'setSpeed',mult:1});
function run(sec:number){advanceFlow(st,sec,[],Math.ceil(sec*20)+1);assert.equal(st.engineer.down,-1,'ordinary route knocked down');}
function walk(x:number,y:number){const path=findPath(st,Math.floor(st.engineer.x),Math.floor(st.engineer.y),Math.floor(x),Math.floor(y));assert.ok(path,`reachable ${x},${y}`);for(const t of path){const tx=t%G.tw+.5,ty=Math.floor(t/G.tw)+.5;let ticks=0;while(Math.hypot(tx-st.engineer.x,ty-st.engineer.y)>.23){assert.ok(ticks++<60,`walking blocked ${t}`);const dx=tx-st.engineer.x,dy=ty-st.engineer.y,n=Math.hypot(dx,dy);cmd({type:'walk',dx:dx/n,dy:dy/n});run(.05);}}cmd({type:'walk',dx:0,dy:0});}
function near(x:number,y:number,size=1){for(let radius=1;radius<7;radius++)for(let dy=-radius;dy<=radius;dy++)for(const dx of [-radius,radius])if(!(dx>=0&&dx<size&&dy>=0&&dy<size)&&passable(st,x+dx,y+dy)&&findPath(st,Math.floor(st.engineer.x),Math.floor(st.engineer.y),x+dx,y+dy)){walk(x+dx,y+dy);return;}throw Error('No reachable interaction position');}
function mine(item:Item,count:number){const target=(st.engineer.inv[item]??0)+count;while((st.engineer.inv[item]??0)<target){const home=G.blocks[st.campaign!.homeBlock];let pick:{x:number;y:number}|null=null;for(let y=home.y0;y<home.y1&&!pick;y++)for(let x=home.x0;x<home.x1;x++){const r=rubbleAt(st,x,y);if(r?.type===item&&!r.persistent){pick={x,y};break;}}assert.ok(pick,`bootstrap ${item}`);near(pick.x,pick.y);cmd({type:'mineAt',...pick});const before=st.engineer.inv[item]??0;while((st.engineer.inv[item]??0)<target&&st.flow!.hand.mine)run(.05);assert.ok((st.engineer.inv[item]??0)>before);cmd({type:'mineAt',x:-1,y:-1});}}
function build(kind:Kind){const home=G.blocks[st.campaign!.homeBlock];for(let y=home.y0;y<home.y1;y++)for(let x=home.x0;x<home.x1;x++)if(blockOfTile(st,x,y)===st.campaign!.homeBlock&&canPlace(st,kind,x,y).ok){near(x,y,kind==='turret'?2:3);cmd({type:'construct',edits:[{action:'place',item:kind,x,y,dir:1}]});assert.ok(actionResult(st).ok,actionResult(st).reason);return st.flow!.machines.at(-1)!;}throw Error('No legal '+kind);}
try{
 assert.deepEqual(st.engineer.inv,{});assert.equal(st.stock.steel+st.stock.copper+st.stock.stone+st.buffer,0);assert.ok(!st.flow!.machines.some(m=>m.kind==='generator'));
 mine('steel',180);mine('copper',75);mine('coal',45);milestones.push({step:'hand-gathered bootstrap inputs',seconds:st.t,inv:{...st.engineer.inv}});
 const generator=build('generator');cmd({type:'factory',action:{type:'feed',x:generator.x,y:generator.y}});assert.ok(actionResult(st).ok);
 // Excavator must overlap a deposit, and is paid from the same mined stock.
 const home=G.blocks[st.campaign!.homeBlock];let excavator=false;
 for(let y=home.y0;y<home.y1&&!excavator;y++)for(let x=home.x0;x<home.x1;x++)if(blockOfTile(st,x,y)===st.campaign!.homeBlock&&rubbleAt(st,x,y)?.type==='coal'&&canPlace(st,'excavator',x,y).ok){near(x,y,3);cmd({type:'construct',edits:[{action:'place',item:'excavator',x,y,dir:1}]});assert.ok(actionResult(st).ok);excavator=true;break;}
 assert.ok(excavator);assert.ok(machineRunning(st,st.flow!.machines.find(m=>m.kind==='excavator')!),'paid excavator has real power');const assembler=build('assembler'),turret=build('turret');
 const [wx,wy]=workbenchTile(st);walk(wx,wy);cmd({type:'factory',action:{type:'craft',item:'magazine',count:8}});assert.ok(actionResult(st).ok,actionResult(st).reason);run(49);assert.ok((st.engineer.inv.magazine??0)>=8);near(turret.x,turret.y);cmd({type:'factory',action:{type:'feed',x:turret.x,y:turret.y}});assert.ok(actionResult(st).ok);milestones.push({step:'paid production, fuel and loaded defence',seconds:st.t,majorAt:st.campaign!.defence!.nextDawn+900});
 // Retain scouting ammo after loading the hopper.
 walk(wx,wy);cmd({type:'factory',action:{type:'craft',item:'magazine',count:6}});run(37);
 const core=st.campaign!.progression!.sites.find(s=>s.item==='core1')!;near(core.x-7,core.y);run(.1);
 for(let i=0;i<800;i++){const enemy=st.flow!.threat!.crawlers.filter(c=>core.guards?.includes(c.id)).sort((a,b)=>Math.hypot(a.x-st.engineer.x,a.y-st.engineer.y)-Math.hypot(b.x-st.engineer.x,b.y-st.engineer.y))[0];if(!enemy)break;cmd({type:'aim',at:[enemy.x,enemy.y]});run(.05);}
 cmd({type:'aim',at:null});assert.ok(core.guards?.every(id=>!st.flow!.threat!.crawlers.some(c=>c.id===id)),'first core defenders beaten with bootstrap Shot');near(core.x,core.y);cmd({type:'progression',action:{type:'recover',id:core.id}});assert.ok(actionResult(st).ok,actionResult(st).reason);assert.equal(st.engineer.inv.core1,1);writeFileSync('docs/evidence/gameplay-corrections/core-recovered-save.json',JSON.stringify(makeSave(st,{log,logComplete:true})));
 const plant=st.campaign!.progression!.sites.find(s=>s.kind==='plant')!;near(plant.x,plant.y);cmd({type:'progression',action:{type:'deliver',id:plant.id}});cmd({type:'progression',action:{type:'activate',id:plant.id}});assert.ok(actionResult(st).ok,actionResult(st).reason);assert.equal(plant.installed,'core1');milestones.push({step:'first core recovered and chosen plant activated without grants',seconds:st.t,hp:st.engineer.hp});
 assert.equal(stateProblem(st),'');assert.ok(conservation(st).ok,conservation(st).problems.join(';'));
 writeFileSync('docs/evidence/gameplay-corrections/ordinary-save.json',JSON.stringify(makeSave(st,{log,logComplete:true})));writeFileSync('docs/evidence/gameplay-corrections/ordinary-result.json',JSON.stringify({milestones,ledger:conservation(st),commandCount:log.length},null,2));console.log(JSON.stringify(milestones));
}catch(error){writeFileSync('docs/evidence/gameplay-corrections/ordinary-failure.json',JSON.stringify({error:String(error),milestones,t:st.t,inv:st.engineer.inv,position:[st.engineer.x,st.engineer.y],state:st}));throw error;}
