from pathlib import Path
import json
root=Path(__file__).resolve().parents[4];out=Path(__file__).resolve().parent
read=lambda p:p.read_text(encoding='utf-8-sig')
assert '# pass 370' in read(out/'test.log') and '# fail 0' in read(out/'test.log')
assert '# pass 35' in read(out/'focused-final.log')
b=json.loads(read(out/'browser-result.json'));assert len(b['rows'])==6 and not b['errors']
for n in ['CLAUDE.md','README.md','docs/PROGRAMME_STATE.md','docs/PHASES.md','docs/EXPLORATION_DEFENCE_PLAN.md','docs/STANDARDS.md']:
 p=root/n;s=read(p).replace('RI-02B-UI-04 is next','RI-02B-UI-05 is next')
 if n=='CLAUDE.md':
  a=s.index('Current task pointer:');z=s.index('\n\n',a);s=s[:a]+'Current task pointer: RI-02B-UI-05 is next: Projects, restoration service circuits and actionable alerts. UI-01–04 shell, HUD, building controls and inspection/inventory are complete; evidence is in docs/evidence/ui-redesign/README.md. P9-05 remains frozen on port 5181 and P9-H remains available. PROGRESS owns execution order.'+s[z:]
 if n=='README.md':
  s=s.replace('**Next implementation: RI-02B-UI-04 — machine inspection, inventory and diagnostics.**','**Next implementation: RI-02B-UI-05 — Projects, restoration service circuits and actionable alerts.**').replace('UI-01–03 shell, HUD and building controls','UI-01–04 shell, HUD, building and inspection controls').replace('Deeper inspection/projects and settings/scaling remain in UI-04–06.','Machine inspection and separate inventory stores are implemented; deeper Projects and settings/scaling remain in UI-05–06.')
 if n=='docs/PROGRAMME_STATE.md':
  a=s.index('Current handoff:');z=s.index('\n\nPrior city/construction handoff:',a)
  s=s[:a]+'Current handoff: 2026-09-09. **RI-02B-UI-04 is complete:** operating-first machine inspection, multiple applicable sim blockers, separate measured/nominal/local-circuit facts, identity-preserving pin/removal handling, known-input help/location and scoped Home/chest/station/truck transfers. Existing settings, station requests, cargo and construction delivery commands remain authoritative. [Evidence](evidence/ui-redesign/README.md); [mutable UI preview](http://127.0.0.1:5178/?rules=exploration-v2&seed=3&view=world&state=/ui-fresh.json). 370 full tests, 35 focused tests, types/build/lint and both-width identity/settings/transfers/input/save/replay checks pass. Archives bind 214 inputs and 13 changes against UI-03. UI-05 is next for Projects, restoration circuits and actionable alerts. Save schema, costs, city generation and campaign fingerprint remain unchanged. Human verdicts and existing performance findings remain open.'+s[z:]
  s=s.replace('and UI-01–03 implementation are local changes','and UI-01–04 implementation are local changes').replace('now including UI-03','now including UI-04')
 p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/PROGRESS.md';s=read(p).replace('**Next implementation (2026-09-09, D-UI-05):** RI-02B-UI-04, machine inspection, inventory and diagnostics. UI-01–03 shell, HUD and building controls are complete','**Next implementation (2026-09-09, D-UI-06):** RI-02B-UI-05, Projects, restoration service circuits and actionable alerts. UI-01–04 shell, HUD, building and inspection controls are complete')
s=s.replace('| RI-02B-UI-04 | Machine inspection, inventory and diagnostics | agent | in_progress |','| RI-02B-UI-04 | Machine inspection, inventory and diagnostics | agent | done |').replace('| RI-02B-UI-05 | Projects, restoration service circuits and actionable alerts | agent | blocked |','| RI-02B-UI-05 | Projects, restoration service circuits and actionable alerts | agent | todo |')
s='\n'.join(line.replace('pending — docs/evidence/ui-redesign/README.md | |','docs/evidence/ui-redesign/README.md UI-04; ui-04/verification.json | 2026-09-09 |') if line.startswith('| RI-02B-UI-04 |') else line for line in s.splitlines())+'\n'
s+='\n- 2026-09-09 — RI-02B-UI-04 done under D-UI-06: operating-first inspection, multiple sim blockers, stable pinned/removed identity, separate transfer stores and truthful previews; existing recipe/filter, freight and truck commands preserved. 370 full + 35 focused tests, types/build/lint, both-width inspection/transfers and shell input/save/replay checks pass. UI-05 blocked → todo. Frozen evidence and human gates remain intact; no commit or push.\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/DECISIONS.md';s=read(p);assert '### D-UI-06 ' not in s
s+='''
### D-UI-06 — UI-04 inspection, scoped inventory and diagnostics (2026-09-09)

**Authority:** owner (current user), “Ok onto UI-04”. Implements D-UI-01 after UI-03. Engineering implementation is separate from human usability/gameplay acceptance.

**Implementation choices (agent):** one identity-based inspector orders name/location, operating statement, measured useful output, inputs, current constraints, existing actions and collapsible detailed rates/circuit/contents. Pin retains identity through building and Escape cancellation; a removed ID shows a dismissible removed card and never retargets replacement coordinates. A read-only sim constraint query combines the existing power/disabled and operating predicates; current missing inputs and output space are independent, while shortages for an already-running next batch are labelled separately. No-load remains neutral, and unmeasured throughput remains unavailable. Missing-input help links the existing item guide and only real known Home supplies/finite patches. Camera location is presentation only.

One transfer drawer keeps pockets, Home/chest stock, stop platform, arrivals and reserved inbound distinct. Target identity is preserved when removed. Existing transfer quantities/actions remain; read-only previews use pool/reach/stack/capacity predicates, including partial amounts and arrival-first station withdrawal. Truck preview is extracted from its command validator; cargo remains physically separate. Recipe/filter/priority, hand craft, station requests and construction delivery retain normal validated commands. Precise production/power figures remain in Management and inspection Details, outside Developer. UI-05 owns project circuits/alerts and UI-06 owns full settings/scaling/integration.

**Evidence/handoff:** [UI-04 evidence](evidence/ui-redesign/README.md): 370 full and 35 focused tests, types/build/lint, both-width paid identity/settings/transfers/save/replay and input checks plus actual working/stalled images. UI-05 is next. Save/session schema, campaign fingerprint ba11e896, city generation, harness and frozen UI-03/P9/EX-08D evidence are preserved. Human gates, P6-AMMO, Q07 and performance findings remain open. No commit or push.
''';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/RI-02B_UI_SPEC.md';s=read(p)+'\n- 2026-09-09 — D-UI-06 / UI-04: operating-first inspection, multiple sim blockers, identity-preserving pin/removal handling and separate inventory/cargo previews delivered; settings/freight/truck commands preserved. Projects/service circuits remain UI-05. [Evidence](evidence/ui-redesign/README.md).\n';p.write_text(s,encoding='utf-8',newline='\n')
p=root/'docs/RELIGHT-design.md';s=read(p).replace('UI-01–03 deliver the shared shell/input, tokens, core HUD, truthful opening guidance and catalogue/quickbar/placement controls; deeper inspection/projects and settings remain planned.','UI-01–04 deliver the shell/input, tokens, core HUD, opening/build guidance and operating-first inspection with separate inventory stores; deeper Projects and settings remain planned.');s+='\n- 2026-09-09 — D-UI-06: UI-04 inspection, multiple read-only blockers, scoped transfers and diagnostics delivered; progression, prices and production transitions unchanged.\n';p.write_text(s,encoding='utf-8',newline='\n')
print('UI-04 handoff updated; UI-05 next; human gates preserved.')
